### ISSUE TITLE
Extract and Remux dialog defaults

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#103]
The extract audio dialog used to enable mix to mono and decimate by default, which I think made perfect sense, but it no longer does.

On the remux audio dialog, I think there are some defaults that would make sense as well:
1. Select the default video stream rather than No Video
2. For signal mapping, could they default to using the signal that is loaded if there is only one signal loaded, or could there at least be a convenient way to apply a signal to all channels at once?

**Comment by 3ll3d00d** [comment]
added preferences for the checkboxes and a quick way to apply a single filter to all channels
