### ISSUE TITLE
Add the ability to apply a fractional octave smoothing to the charts

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#108]
only really useful for full range signals

**Comment by aron7awol** [comment]
I'd like to revisit the idea of trying to identify and adjust for mixes that are quieter/louder than average.  Some sort of smoothing like this would be really helpful for that.

Side question: You aren't using dialnorm in any way in BEQ Designer, are you?  As part of this volume normalization process, I am thinking about how dialnorm comes into play.  If most AVRs use dialnorm to adjust the volume, and that results in a difference in playback volume, maybe we could optionally check that flag in BEQ Designer and account for the effect it will have down the line?  Any thoughts on this?

**Comment by 3ll3d00d** [comment]
hard to find a definitive answer on this but I believe it is applied by default by libavcodec based on the stream metadata but can be overridden with some arbitrary value via a (not obviously documented) command line switch

**Comment by 3ll3d00d** [comment]
It isn't obvious to me how dialnorm is relevant though in this case. As far as I know it is just an overall volume level adjustment so it doesn't affect the intrachannel balance, i.e. it just turns it down a few dB based on the value in the metadata.

**Comment by aron7awol** [comment]
I agree with you.  I actually went back and editing my post above removing that second paragraph but then decided to leave it to at least get your thoughts.

Is there an easier built-in method of smoothing in the charting library that you could quickly and easily enable?  I was just trying to compare the high ends of the graphs and they are really difficult to compare visually without any smoothing, and really, any method of smoothing would be extremely helpful.

**Comment by 3ll3d00d** [comment]
There is nothing built in as such, would require some implementation of a smoothing/averaging algorithm

**Comment by aron7awol** [comment]
Gotcha, I only thought there might be because you mentioned previously you had done some smoothing of the graph vs. the jagged line of SpecLab.

**Comment by aron7awol** [comment]
Actually, increasing the analysis resolution smooths the curve.  Is it easy to add some additional options higher than 4Hz to that?

**Comment by 3ll3d00d** [comment]
I wouldn't trust that to give the information you address looking for so not going to add that. 

This is where you want either a constant q transform (basically a wavelet approach, underlying lib supports this but I don't know how to use it) or a fractional octave smoothing (which create fractional octave sized bins to group the fft bins by and which I do know how to implement but haven't got round to) 

You could possibly export the chart as frd and feed into rew or similar as a quick hack

**Comment by aron7awol** [comment]
My thinking was that I was trying to sort of compare the average level of the peak graphs of two different mixes, and that by making the buckets bigger I would be averaging with the surrounding buckets to some extent.

Thinking about this more, if we played some repeating complex sounds and told someone to turn it up as loud as they could without it being uncomfortable, what would be the limiting factors?  Certainly frequency would be an important component, as our ears can handle lower frequencies better, and I would think the peak levels would be more important than the average levels.  Thus, perhaps looking at the peaks of the peak graph would be more important than looking at the average of the peak graph?

**Comment by 3ll3d00d** [comment]
Peaks at low frequencies certainly dictate how loud you can take it, at high frequencies I think it gets a bit more complicated as some sounds are much more wearing than others. The capability of the speakers are a big factor in this as well. 

Ultimately I think this just comes down to using one of the existing standard loudness metrics, I would guess ebu r128 is the way forward.

**Comment by 3ll3d00d** [comment]
@aron7awol this is in 0.5.3 however pls bear in mind https://github.com/3ll3d00d/beqdesigner/issues/175 so I would concentrate on the shape not the absolute level

**Comment by aron7awol** [comment]
Is it possible to use fractional octave smoothing on files that are resampled to 8kHz?

**Comment by 3ll3d00d** [comment]
It is possible for sure, just needs some work to either make smoot selectable by the user or change the minimum sample rate at which it is applied

**Comment by aron7awol** [comment]
Gotcha, I was just trying to get it to happen and couldn't figure out a way to, so I just wanted to double-check that I wasn't doing something wrong :)  It works fine on full range, it's just that full range is so painfully slow (as you know) compared to 8kHz which is a nice happy medium.
