### ISSUE TITLE
Headroom shown inconsistent with Audacity

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#115]
I loaded my 1000Hz track of Ready Player One and the app says I have 6.915dB of headroom.

Audacity says the same track has 3.003dB.

**Comment by aron7awol** [comment]
Now I loaded the BEQ and it says I have -23.707dB of headroom.

Compare this to the 1.015dB of headroom I got after remuxing the same filters and checking in Audacity.

**Comment by aron7awol** [comment]
Just for another data point for you, I also loaded the remuxed file with BEQ applied and it says I have 2.336dB of headroom (compared to that same 1.015db in Audacity).  So in both cases the app is showing 2.3x as much headroom as Audacity

**Comment by 3ll3d00d** [comment]
where is the headroom shown in audacity?

**Comment by 3ll3d00d** [comment]
there were a couple of daft bugs which I've fixed

I did quick compare by

* extract TIH LFE channel, headroom is <1dB
* add a +4dB 30Hz LS Q=0.7
* check waveform with filter, is clipping by a few dB
* remux
* check remuxed waveform with filter, looks same as the in memory version

**Comment by 3ll3d00d** [comment]
released in https://github.com/3ll3d00d/beqdesigner/releases/tag/0.4.4

I don't know what audacity is reporting but this is based the absolute max sample value and the headroom is the ratio of 1 to that, i.e. `20*log10(1.0/maxSampleValue)`

**Comment by aron7awol** [comment]
To check headroom in Audacity I select the entire track then goto Effect...Amplify and it will default to the amount of headroom left, because the "Allow clipping" checkbox will be unchecked by default.

**Comment by 3ll3d00d** [comment]
ok, from a quick look that appears to use the peak positive sample... not sure why they ignore the peak negative sample but I doubt that will make much difference in practice (i.e. would expect to be within a few thousandths of a dB). 

If you see a markedly larger delta then I probably need a sample I can try myself, something like a 5 minute snippet of a track + a saved filter would probably be sufficient.

**Comment by aron7awol** [comment]
Okay, I'll re-test this functionality with the new release at some point tonight.
