### ISSUE TITLE
Peak spectrum display tweaks

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#116]
There is so much data that even if I take up the entire vertical real estate on my screen, a high level point is easily hidden under a bunch of lower level points.  I am wondering what tweaks we could do to improve the display.

Some thoughts...
1. Maybe that other spectrum display that you previewed in the thread on AVS?
2. How big are the time buckets for the data points on the peak spectrum graph?  If they are the same as what the PvA graph is based on, I could see why you'd want to stick to that if possible, so that the levels match between the two graphs, but bigger buckets would obviously reduce the number of data points.
3. Reduce the size of the displayed data points, and maybe try a square shape?

Also, I was thinking I'd like to set a specific dB level to clip at, rather than use something that will vary per film.  I was looking for a clipping point that I could use on multiple films and have it be a consistent cutoff rather than something relative to the mix.  That way someone can look at peak spectrums for different films and kind of compare apples to apples.

**Comment by 3ll3d00d** [comment]
Re 1, which one do you mean?

Re 2, this is the time/freq resolution tradeoff , as resolution on one axis goes up, the other goes download. The spectrogram view lets you see this. This view is fixed to that used in the PvA graph.

Re 3, can try this

Re 4, can see where you are coming from but the listener has a volume control so they can turn up quiet tracks, this would misrepresent the comparison in that case. Clip to absolute peak is arguably the volume control insensitive version of this (if you assume this puts a limit on how much you can turn it up anyway)

**Comment by 3ll3d00d** [comment]
Did you play with the colour range value, if not using clip to absolute peak then iirc reducing this will limit the amount of data shown.

**Comment by aron7awol** [comment]
I was referring to the spectrogram view in 1, but wasn't sure if you could go small enough with the pixels to display the entire track, even if one pixel represented a data point.

I did play with the color range value, and I can tweak that to limit the bottom end of what points show up.  So, given that, which I think is an acceptable workaround for what I'm trying to achieve, that only leaves one issue which is that the top end will vary from mix to mix.  I'd really like to get a color scale that's consistent from mix to mix so that we can compare apples to apples, so I'd like to be able to specify the top and bottom end of the color scale.

I can see where you're coming from as well with the user having volume control so they can turn up quiet track, and that clip to absolute peak is arguably a volume control insensitive version of this.  The only thing I'll say about that is that in my experience, it is not the volume of the bass that determines how high I can turn my MV, it is the volume of the treble.

This kind of ties into why I wanted to use the higher sample rates to see the higher part of the graph so I could try to predict the maximum MV for a particular track based on my experience and try to level the playing field, so to speak.  I'm looking at that as a separate issue for me to try to experiment with in the near future.

**Comment by 3ll3d00d** [comment]
> I was referring to the spectrogram view in 1, but wasn't sure if you could go small enough with the pixels to display the entire track, even if one pixel represented a data point.

the existing view is basically a spectrogram that can be rendered very quickly and which focuses on the stronger signals, i.e. it is a workaround for the fact it's not feasible to render the spectrogram directly

> I'd really like to get a color scale that's consistent from mix to mix so that we can compare apples to apples,

I think a technically correct way to do this would be to calculate a reference volume level for the (full range) track and then adjust the colour range accordingly. [R128](https://tech.ebu.ch/docs/tech/tech3342.pdf) is I think the international standard for this and ffmpeg does actually have an implementation of this (https://ffmpeg.org/ffmpeg-filters.html#ebur128-1) so I imagine it won't be too hard to analyse the track to calculate this reference value (i.e. an offset).

> With Atomic Blonde, the top value actually varies between the original and BEQ versions, so it's not even consistent within the same film, never mind between films. 

I am thinking to break this down into a few steps

* tweak the rendering of the existing view to accommodate the data better on screen
* change the controls on this form (as they are quite confusing), TBD exactly how to do that but involves being able to control the range more directly
* add R128 analysis and reference offsets, use this to enable comparisons across tracks

thoughts?

**Comment by aron7awol** [comment]
Very interesting and promising, and definitely seems like a technically sound way of doing it.  In the meantime, I think manual control over the limits of the color bar would be a decent compromise.  That at least would give the people in the BEQ thread a consistent point of reference, at least as much as the PvA graphs are consistent with each other and people compare them film to film by seeing what levels they peak at.  Essentially, ignoring the difference in overall volume of a track, the status quo until we can give them a good way to adjust for it.

I'm guessing there's no way for you to control which data points appear on top of others?  Otherwise, it would be preferable to have higher level points overlap lower level points, which would make the plot actually sort of appear 3D and show the peaks even when there's so much data that it overlaps.
