### ISSUE TITLE
Change z order in the audio analysis spectrum plot

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#117]
sort the stacked spectrogram data into ascending magnitude order so the scatter plot renders the most intense values last (i.e. on top)

_Originally posted by @3ll3d00d in https://github.com/3ll3d00d/beqdesigner/issues/116#issuecomment-430795625_

**Comment by aron7awol** [comment]
I think this would go a long way toward making the plot more readable when there is a lot of data.
