### ISSUE TITLE
Error when selecting filter in peak spectrum view

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#123]
![image](https://user-images.githubusercontent.com/42757020/47272054-e078a080-d54d-11e8-8da2-76dc122ce8a1.png)

**Comment by 3ll3d00d** [comment]
exactly when does this happen? i.e. what is the state of the screen at the time you select a filter? which filter did you select (adding a filter or removing it)?

**Comment by aron7awol** [comment]
1. Open analysis screen
2. Select wav file and click Load
3. Change filter dropdown from No Filter to the set of the filters I want to use
Error occurs on step 3

**Comment by aron7awol** [comment]
If I click the refresh button I get a very similar error:
![image](https://user-images.githubusercontent.com/42757020/47272674-25550500-d557-11e8-840d-881b56707fc9.png)

If I click the Load button again it stops the errors from occurring anymore

**Comment by 3ll3d00d** [comment]
Fwiw it does work if you select the filter before loading

**Comment by aron7awol** [comment]
Ok, I'll just do it in that order from now on.
