### ISSUE TITLE
Marker type hline

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#124]
Thanks for adding all those marker types!  Do you mind just adding one more?  I'd like to experiment with the "hline" marker type.

**Comment by 3ll3d00d** [comment]
the reason it's not in the list is because it's not a filled marker and it only gets wider (not thicker) as the size goes up, this means it will be prone to either leaving gaps on the y axis and/or produces a fairly misleading impression of temporal accuracy

**Comment by aron7awol** [comment]
I figured the chances of leaving gaps on the y-axis are slim, at least with a full movie graph?  I really just want to try it out and see what it looks like.  Please?

**Comment by 3ll3d00d** [comment]
It leaves gaps if the time period is short enough, looks v "thin" if it is longer. I can add it though.

**Comment by aron7awol** [comment]
Thanks!

I also saw this in the matplotlib marker section:
![image](https://user-images.githubusercontent.com/42757020/47272857-60f0ce80-d559-11e8-9f0c-8e0c975979ad.png)

Not sure if that is reasonable to implement but I scrolled through the symbols and a couple caught my eye...
![image](https://user-images.githubusercontent.com/42757020/47272854-52a2b280-d559-11e8-913f-c6ae8ed5941c.png)
![image](https://user-images.githubusercontent.com/42757020/47272872-91d10380-d559-11e8-9c5a-afdb980dbced.png)

**Comment by aron7awol** [comment]
That horizontal ellipse is kind of what I have been envisioning from the beginning.  I think it will help bridge the horizontal gaps while retaining more vertical resolution, and and the roundness should still make it look smooth.

**Comment by 3ll3d00d** [comment]
I would expect that to require the stix fonts to be installed on the host machine. It is possible to define a custom marker though and make that into an ellipse, e.g. https://matplotlib.org/gallery/lines_bars_and_markers/scatter_custom_symbol.html

I think at this point it's worth taking a step back and asking what we actually want. The original intent of that chart was to highlight the big hitting sections quickly, hence the use of a scatter plot as a fast way to deliver this. However it is now being used to visualise the all the content on the entire track and thinking of ways to use a custom marker to fill in the gaps on a scatter plot. If this is really what people want to see then the chart just needs a spectrogram mode (which will render using [pcolormesh](https://matplotlib.org/gallery/images_contours_and_fields/pcolormesh_levels.html#sphx-glr-gallery-images-contours-and-fields-pcolormesh-levels-py) or [imshow](https://matplotlib.org/gallery/images_contours_and_fields/interpolation_methods.html#sphx-glr-gallery-images-contours-and-fields-interpolation-methods-py) or contourf though that is likely to be v v slow) and you have to accept that it might be quite slow to render.

**Comment by aron7awol** [comment]
I agree with everything you're saying and I do think the scatter is a nice compromise for what we're trying to accomplish, rather than using a true spectrogram mode that will render slowly.  Really, I'm 95% satisfied with it as-is with the circle/point markers, so I'm not trying to reinvent the wheel and don't want to turn this into a huge ordeal.  It's just one of those things where I was visualizing an ellipse marker and I think the fact that it will show more vertical resolution would be a benefit.  When I experiment with the different marker sizes, I am making the circle/point markers bigger than I really want to just because that's what it takes to make them overlap horizontally.  I think a horizontal ellipse would allow me to keep the markers smaller vertically, which I think is preferable.  If you are willing to add the functionality of the custom ellipse markers, I'd really appreciate if you would allow me to experiment with them a bit.

**Comment by 3ll3d00d** [comment]
I did attempt to add the custom ellipses the other day but I couldn't work out the incantation required. I might try pcolormesh again and time it as a scatter with that many points is still pretty slow so it might not be any slower.

**Comment by 3ll3d00d** [comment]
example is TIH

this is pcolormesh, i.e. a fairly typical way to plot a spectrogram

![image](https://user-images.githubusercontent.com/2487509/47323505-f7091f80-d653-11e8-9a65-a20166f8cc35.png)

this is a scatter plot using marker = point, size 1

![image](https://user-images.githubusercontent.com/2487509/47323533-199b3880-d654-11e8-85be-997cd8b7cb65.png)

you can see how much more the latter pops as it gives *much* more weight to the strong content

**Comment by 3ll3d00d** [comment]
zooming into a few mins worth of content, comparing pcolormesh and points again

![image](https://user-images.githubusercontent.com/2487509/47323700-ce355a00-d654-11e8-8ec4-eba156c6376f.png)

![image](https://user-images.githubusercontent.com/2487509/47323687-bcec4d80-d654-11e8-8f38-da73126506a5.png)

these are more similar than different, debatable which one works best

**Comment by 3ll3d00d** [comment]
same again but with gouraud shading on pcolormesh

![image](https://user-images.githubusercontent.com/2487509/47323776-1eacb780-d655-11e8-90e9-2f67185afa10.png)

this is closer still to the point version

**Comment by 3ll3d00d** [comment]
tricontourf version using 0.5dB steps for the contours

full track

![image](https://user-images.githubusercontent.com/2487509/47324149-9deebb00-d656-11e8-877c-683d27b76ba4.png)

![image](https://user-images.githubusercontent.com/2487509/47324188-beb71080-d656-11e8-8a2f-839ccd9bb36e.png)

**Comment by 3ll3d00d** [comment]
tricontourf falls between the two pcolormesh versions  (flat vs gouraud shading) in terms of how it looks imv, it clearly accentuates the high notes better than the flat pcolormesh without going quite as far as the point scatter plot. 

I think it's reasonable to argue tricontourf is the most accurate rendition of an entire track but it's debateable whether strictly accurate is the goal here as opposed to giving an artists impression.

**Comment by 3ll3d00d** [comment]
in terms of rendering speed, it is (fastest first) pcolormesh then scatter then tricontourf

**Comment by 3ll3d00d** [comment]
my conclusion, I'll offer the following options

* pcolormesh (flat)
* pcolormesh (gouraud)
* tricontourf 
* point scatter with variable sizes 

this means I'll remove the other marker options as they seem redundant to me

I don't believe I can get custom ellipses working reliably in any reasonable timeframe so I'm not going to go there

**Comment by 3ll3d00d** [comment]
NB: won't be making this change particularly soon so @aron7awol feel free to provide your view on the above

**Comment by aron7awol** [comment]
They all look very interesting, and I'd really like to play around with all of them at some higher zoom levels to be able to figure out what I like and don't like about each of them.

Can we keep some of the simpler marker options?  circle, point, square, hexagon2 are the ones I like best as-is.  I also saw in the documentation that markers can be rotated, and I thought the thin diamond rotated 90 degrees might actually work really well.  Could you throw that in the mix as a much-simpler-to-implement alternative to the ellipse?

I think I saw on AVS you posted a peak spectrum with 0.5Hz resolution?  I think I tested that a long time ago and I think it ended up lowering the peaks since there were more buckets so some of the highest peaks were getting spread out?  Is that true and expected?  I ask because it's a nice way to fill in the gaps by having more data points horizontally without zooming out, and the peak spectrum you posted looked really nice because of it.

**Comment by aron7awol** [comment]
The more I look at these the more I agree with you that the point makes the strong content pop more than all of those, which is a good thing.  Unfortunately, this keeps bringing me back to the ellipse, which would retain area which would translate to the pop, while having more vertical resolution than the circle.  It's really too bad it's so difficult to implement! I wish I could help with it.

After testing, I think a circle is exactly twice the size of a point?

**Comment by aron7awol** [comment]
I did some more testing.  The point is great.  Sorry I was a pain on this.  The point is good enough and I'm happy enough with it.

**Comment by aron7awol** [comment]
I changed that setting in the past when playing with the PvA graphs, and I think it ended up lowering the peaks, which I assumed was due to there being more buckets so the data was getting more spread out?

If that is true, and the same thing would happen with the spectrum scatter, then the only thing I don't like about that is that I'm kind of changing the data from what is on the PvA graph, and the peaks won't be as high.

Ellipses!  Are they slow to render because it is actually rendering multiple points in order to create the ellipse?

**Comment by 3ll3d00d** [comment]
Ellipses are no slower to render than points, scatter is just quite slow to render full stop when the number of markers is large.

It just depends re bins, the freq range is smaller but the length of time included is longer so the amount of energy in that bin will be different. I would guess less energy per bin will be the norm though.
