### ISSUE TITLE
Save preferences for spectrum settings and window size?

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#127]
The ellipses work/look awesome!  Thank you!

Is there any way for me to save some of the settings on the screen as defaults?
Marker type
Marker size
Ellipse width & height
Frequency

Also, the other windows (main window, report window) remember what size I resized the window to last time, so I don't have to adjust it every time.  For some reason, the peak spectrum window always resets itself to the default small size.  I have tried to work around this by installing the freeware app AutoSizer, but for some reason it doesn't detect and auto-size this window as it is supposed to.  Any ideas?

**Comment by 3ll3d00d** [comment]
The geometry of the other windows is saved by the app and restored on load. Will add the same here.

**Comment by 3ll3d00d** [comment]
@aron7awol  fixed in https://github.com/3ll3d00d/beqdesigner/releases/tag/0.4.6
