### ISSUE TITLE
Error when saving report with local jpg image

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#140]
![image](https://user-images.githubusercontent.com/42757020/48302994-80cd3f80-e4d2-11e8-97eb-40994099ed6a.png)

**Comment by aron7awol** [comment]
It seems to work in beta.3 with the same image, but not in beta.4 or beta.5

**Comment by 3ll3d00d** [comment]
I didn't change the report so that's odd

any particular image involved?

**Comment by aron7awol** [comment]
![alpha-art](https://user-images.githubusercontent.com/42757020/48304111-b3326900-e4e1-11e8-9fcf-3c72f1dbc1b7.jpg)

**Comment by 3ll3d00d** [comment]
thanks for spotting it, fixed in https://github.com/3ll3d00d/beqdesigner/releases/tag/0.5.0-beta.6
