### ISSUE TITLE
New filters are being created when editing an existing filter and saving

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#141]
This is in this new beta.6 release.

**Comment by aron7awol** [comment]
If I create two filters, the first one suffers from this problem (saving as new even when editing an existing filter) but the second doesn't.  If I edit one of the filters that spawn from trying to edit the first filter, those also keep spawning new filters rather than saving as an edit.

**Comment by 3ll3d00d** [comment]
thanks for noticing this one, fixed in https://github.com/3ll3d00d/beqdesigner/releases/tag/0.5.0-beta.7

**Comment by aron7awol** [comment]
It seems to be stable now, thanks!
