### ISSUE TITLE
Minor filter dialog enhancements

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#143]
The new interface you added for switching between Add New Filter and existing filters from within the dialog is awesome!

There are only a few more minor things that would make it pretty much perfect for BEQ...

1. When saving a new filter, the dropdown box selects the new saved filter, as the user is now editing that filter.
2. Default frequency to something like 20Hz (this is much closer to a typical BEQ filter than 40Hz)
3. Default Q to 0.9 (most common Q and can use the up and down hotkeys to increment by 0.1 from there)

**Comment by 3ll3d00d** [comment]
I don't agree with all of these but have made some tweaks that make things a bit more user controllable

On 1. , I have added the + button back and it is enabled when adding a new filter only, this means save and add another one (i.e. the dropdown will stay on add new filter) whereas the existing save button means save and go into edit mode. Rationale for existing behaviour is that it previews the effect of adding the new filter so adding another new one next is a natural thing to do. I can see how both options can be useful though.

On 2. & 3. I have added preferences for Q and Freq, only applies on first load though as the existing behaviour lets you copy values from an existing filter which IMV is preferable (as it allows you to add more tweaking as you go)
