### ISSUE TITLE
Skip preview on signal add

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#144]
As I play with more full-range signals which take significant time to load, the preview step takes up time and I just end up hitting OK right after anyway.  The OK button is inactive until the signal is previewed.  Can the preview be optional?

**Comment by 3ll3d00d** [comment]
Current build is inefficient as it reads the file n times, next build only reads it once so the delay should be minimised.

**Comment by 3ll3d00d** [comment]
changed the signal dialog so it loads the file and analyses each channel the minimum number of times required to create the signals, the preview button has also been removed as changing the channel selector is enough to choose what to display
