### ISSUE TITLE
Highlight a mix on the graph

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#146]
I'm trying to compare mixes with a large sample of other mixes.  The problem is that it's really hard to even differentiate the one mix I'm trying to look at from the others when there are a bunch already on the graph.  Could you add some way to highlight a mix on the graph?  One thought was to be able to change the thickness of a line on the graph.  What do you think?

**Comment by aron7awol** [comment]
From testing, it looks like you added functionality to click on the actual line to increase/decrease the width.  Is there any other method of doing so?  It's just that it's hard to differentiate between signals on the graph sometimes so if it could be changed via the signal list or even the legend it would make it easy to identify a particular signal on the graph.

**Comment by 3ll3d00d** [comment]
That is correct, speed of implementation won, i.e. this was the quickest way to implement something useful.

Having said that, I didn't find any issues with picking a line on my laptop with 8 channels displayed. The legend is actually already used for visibility purposes so shift clicking on that should make the line v faint (not sure if this still works admittedly, that feature has been a bit flaky)

**Comment by aron7awol** [comment]
I can certainly work around the limitations, I just wanted to double-check that it worked the way it seemed to through trial-and-error testing.

I initially wanted this functionality because I loaded up a whole bunch of "normal" mixes to try to kind of see what an aggregate "reference" curve would look like, and then I loaded a particular mix I was working on to compare, but I couldn't really tell which one it was with so many others on the graph.

Maybe a similarly simple implementation would be an option to "Highlight selected signal" and whichever signal is currently selected gets thicker?

**Comment by 3ll3d00d** [comment]
are you looking for a permanent highlight or a temporary one? i.e. 

temp  = when a button is pressed, the line is highlighted, when you let go, the highlight goes
perm = when some option is selected, the highlight is turned on until you turn it off again

**Comment by aron7awol** [comment]
Permanent in the manner that you are describing, although it wouldn't necessarily need to be something that carries over to the report generator.  For my current purposes, I would use it in the manner I described to compare a mix to a large number of others at once.
