### ISSUE TITLE
0.5.0 beta 10, error adding subtitles...

### ISSUE THREAD

**Issue by hundrakg** [3ll3d00d/beqdesigner#155]
When adding subtitles, it gives error after a short time, when remux....
With no subtitles added it never gives error.
Tried 4 MKV:s with subtitle and without, always stops and gives error with subtitles added, never without...

error:
Command FAILED in 31.226s
.
.
.
[matroska @ 000000000378c800] Application provided invalid, non monotonically increasing dts to muxer in stream 3: 207916 >= 200909
av_interleaved_write_frame(): Invalid argument
frame= 4985 fps=193 q=-1.0 Lsize=  889206kB time=00:03:27.91 bitrate=35035.0kbits/s speed=8.03x    
video:652091kB audio:233906kB subtitle:1473kB other streams:0kB global headers:0kB muxing overhead: 0.195632%
Conversion failed!

**Comment by 3ll3d00d** [comment]
I am simply asking ffmpeg to copy all subtitle streams into the output so I am afraid there is nothing I can do about this sort of thing. 

i.e. you would need to raise it with ffmpeg

**Comment by hundrakg** [comment]
Hello, just wanted to say: Add Subtitles seems to work with VOB Subs. But not with PGS Subs..
Wanted you to know, not that it matters, but maybee you want to now, so you can keep the "Add Subtitle" in further releases, Thanks!

**Comment by 3ll3d00d** [comment]
google tells me that pgs subtitles are problematic for ffmpeg, it's not clear if it is possible to deal with them or whether external tools are required.

This isn't something I'm going to spend time on but if you do research this and find a way for ffmpeg to support this then I will add the right commands to the app

**Comment by 3ll3d00d** [comment]
https://trac.ffmpeg.org/wiki/ExtractSubtitles explains how to see what your ffmpeg supports, on my build hdmv pgs subtitles are listed as decode only (no encode) which I guess is why it fails. I imagine that means it would have to convert the subtitles to another format in order to write them out.
