### ISSUE TITLE
Match gain when including original audio in remux

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#168]
Just throwing this out there since the app already has all of the functionality to create BEQ demo clips by defining timestamps and including original audio...

Since pretty much every BEQ remux requires a negative gain in order to prevent egregious clipping, I think it makes a lot of sense to allow the same negative gain to be applied to the original audio, especially since transcoding is already occurring when cutting at timestamps.

It makes for excellent comparisons, switching back and forth between the two audio tracks.

**Comment by 3ll3d00d** [comment]
It is a good idea however the work required to weave that into the app with a sane ui far outweighs the benefit given the fairly niche use case and the easy workarounds (copy the filter command from the text box, add the right volume filter and then run it manually). Obviously this is not automated but it would be easy to learn how to do it.

**Comment by aron7awol** [comment]
Yeah I thought it would be something you didn't want to spend time on, but figured I'd throw an enhancement out there for the future just in case.

The simplest implementation I thought of was just a text box where the user had to key in the gain rather than go through the trouble of having the app guess based on filters.

I agree it's an easy enough workaround once the user just learns the ffmpeg syntax necessary.

**Comment by aron7awol** [comment]
I think you would add this after the second copy command?
-af "volume=-5dB"

So
copy -map 0:a:0 -c:a:0

becomes
copy -map 0:a:0 -c:a:0 -af "volume=-5dB"

Is that the method you would use?

**Comment by 3ll3d00d** [comment]
seems reasonable in isolation but I suspect you'd have to map the filter correctly if combining with the generated filter_complex

is this change just applying the new offset value to both original audio and filtered audio?

**Comment by 3ll3d00d** [comment]
moved setting offset default to #181

**Comment by aron7awol** [comment]
Questions on how this should be used...

This offset only applies to the original track, correct?

Does the other offset which is specified for the signal apply on remux, or when doing a remux I should use a gain filter?

**Comment by 3ll3d00d** [comment]
This is applied to the original track only. 

The offset applied to the signal when you add it is not used here. 

If you want to adjust gain on the filtered output then you need to add filters to each channel as appropriate
