### ISSUE TITLE
Filter and Clip checkboxes do not apply consistently in the waveform view

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#178]
Load a signal with a waveform
add some filters
check filtered, filters are applied
uncheck filtered, filters are removed
check clipping, filters are applied again == wut

**Comment by aron7awol** [comment]
I don't remember ever encountering this before, but I am doing a demo clip right now, and the waveform isn't applying the Filtered checkbox consistently.  It seems that it applies it only when I first check it, but once I switch to a different channel it reverts.  The strange thing is I did this on another demo clip and didn't have the problem, so I'm trying to figure out what is different about this one.  I'll let you know if I can track it down.
