### ISSUE TITLE
MemoryError when adding full range signal

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#184]
All of the other worked fine, but for some reason, this one fails with error when I select the 48kHz mixed-to-mono wav file:

![image](https://user-images.githubusercontent.com/42757020/50655115-1c23e380-0f5d-11e9-8f6b-db9868f30cfc.png)

It is the Taylor Swift concert from Netflix.  I can upload the file to MEGA if you need it.  It is ~1GB

**Comment by 3ll3d00d** [comment]
`MemoryError` usually means you are out of memory, does it blow if you reopen the app and open that file? What does resource monitor say while you are doing this?

**Comment by aron7awol** [comment]
Memory usage of the app is in fact huge when the error occurs.  What's strange is that it always occurs with that particular file, even if it is the first and only signal I am adding, yet with the others I can add a bunch all at once without issue.

**Comment by 3ll3d00d** [comment]
Odd. Must be something funky about the file. Any clues via ffprobe or mediainfo (or similar)?

If you share it then I will take a look

**Comment by aron7awol** [comment]
Nothing out of the ordinary I can see, especially since it has already been mixed-to-mono and is PCM, so the format is exactly the same as all the others at that point.

I'm uploading it now, should take about 30 mins.

**Comment by aron7awol** [comment]
I was able to get it to load after closing some other apps to free up a bit more memory.  Not sure why this file uses so much more than the others, but at least it works.

**Comment by aron7awol** [comment]
Here's the file in case you want to test it:
https://mega.nz/#!RRlkxQCC!wIWh1QXED2mfO-85s0DWZABlIaxPbz6ZgKXJ9AFj0fQ

**Comment by 3ll3d00d** [comment]
I don't get any particular problem with this file, it consumes ~2G of RAM which seems reasonable.
