### ISSUE TITLE
Specifying a start/end time when adding a signal still loads the entire signal

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#190]

**Comment by aron7awol** [comment]
Do you think this is a new bug?  I'm almost positive I did this recently when I was making demo clips and it worked, although I didn't realize at first I had to click the scissors to get it to apply.

**Comment by 3ll3d00d** [comment]
it is a side effect of the implementation of #144 (which was in 0.5.0-beta.10 so a pretty recent bug)

**Comment by 3ll3d00d** [comment]
ah so the scissors do work

you know useability is not so great when you confuse yourself with your own app design :)

problem is the dark theme I use on my laptop makes it not obvious when something is disabled/enabled
