### ISSUE TITLE
miniDSP file import bug

### ISSUE THREAD

**Issue by bmiller** [3ll3d00d/beqdesigner#196]
The issue with Iron Man can be fixed by changing lines 256-259 in codec.py to:

                    if 'bypass' in inner_filt and inner_filt['bypass'] == '1':
                        del filt[filter_tokens[2]]
                    elif 'boost' in inner_filt and inner_filt['boost'] == '0':
                        del filt[filter_tokens[2]]

The way it's currently written all filters for input 1 or 2 are being deleted when ever a bypassed or boost==0 filter is encountered.  So with how I enter the LS filters 1-x and the Peak on 10 it was always cutting off the peak filters.  I tested it too with bypassing filter 2 which resulted in only filter 1 displaying and if filter 1 is bypassed the app throws an exception.  All tests that I tried passed with the above fix and the expected filters were in the filter tableview.

**Comment by 3ll3d00d** [comment]
the intended behaviour was

    del filts[filter_tokens[1]][filter_tokens[2]]

some slightly misleading naming conventions there :)
