### ISSUE TITLE
7.1 Remux to EAC3 shows 5.1 in the resulting file

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#205]
I know you are just relying on ffmpeg for this eac3 functionality, and from what I've read it seems to support EAC3 7.1, but is there an additional command line switch we are missing?  ffprobe says the resulting file's tracks are 5.1, and so does MediaInfo.  I suppose it's possible that the tracks are in fact 7.1 and those two programs don't recognize it.

**Comment by 3ll3d00d** [comment]
Looks like https://trac.ffmpeg.org/ticket/3595
