### ISSUE TITLE
Waveform Filter state is not carried forward when the selected signal changes

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#207]
I don't remember ever encountering this before, but I am doing a demo clip right now, and the waveform isn't applying the Filtered checkbox consistently.  It seems that it applies it only when I first check it, but once I switch to a different channel it reverts.  The strange thing is I did this on another demo clip and didn't have the problem, so I'm trying to figure out what is different about this one.  I'll let you know if I can track it down.

_Originally posted by @aron7awol in https://github.com/3ll3d00d/beqdesigner/issues/178#issuecomment-454147936_

**Comment by aron7awol** [comment]
Is it possible to get a release that includes this fix?

**Comment by 3ll3d00d** [comment]
Yes at some point, time (and work) is the enemy though!
