### ISSUE TITLE
Question - Level of stereo sources

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#208]
I know stereo sources are only reduced 6dB when mixing-to-mono, vs the 20.2dB/10.2dB reductions the 5.1/7.1 sources get.  I was graphing the BBC show Bodyguard, which is only available in stereo, and as expected, the level shown was significantly higher than normal.

One thought i had was to reduce the level another 14.2dB to total 20.2dB, but after testing that it seemed like too much, and if I BEQed to my "normal" levels based on that the ULF was way too high.  The volume when I play the stereo source also seems very loud in general, despite JRiver's R128 analysis suggesting a MV increase of 4.5dB, I have to listen about 3dB down instead.  This isn't totally unexpected, as I am not surprised that its R128 analysis might work differently for stereo and surround sources.

Essentially what I am wondering is if you know what sort of offset I could add to a stereo->mixed-to-mono track to put it on a level playing field with the surround->mixed-to-mono tracks to be able to use my normal targets for BEQ and end up with similar results?  Do you know if processors typically play stereo tracks louder than they do surround tracks?  In other words, for the same exact digital signal played on a system calibrated to reference, would it being part of a stereo track make the processor play it louder than it would if it were part of a surround track?

**Comment by aron7awol** [comment]
I was imagining a full-scale (105dB if calibrated to reference) sine wave of say 20Hz in a single non-LFE channel of a 5.1/7.1 track that is silent in all other channels.  I believe that would show up as -20.2dB on the graph after it is mixed-to-mono.  I believe the same sine wave in one of the channels of a stereo track (with the other silent) would show up as -6dB on the graph after it is mixed-to-mono.  Do you agree with all of this so far?

But my other separate thought is that with the 5.1/7.1 tracks have an LFE channel which is meant to be mixed 10dB hotter than the rest, and the 2.0 tracks not having the same LFE channel, this would mean that coherent 105dB sine waves in a 2.0 track would only sum to 111dB, and this would be the theoretical maximum of a 2.0 track.  But that didn't really make sense to me, as a single full-scale sine just in the LFE channel of a 5.1/7.1 track would be 115dB!  So I wondered if bass-management worked differently for stereo sources vs surround sources.

I'll keep researching on my own and appreciate you taking the time to discuss this with me.

**Comment by 3ll3d00d** [comment]
Agree with all the above, the lfe channel exists to give that extra headroom after all and the sw channel can get asked to do more and more with the same digital signal level as the channel count rises.

This is why I don't see them as comparable really, they are fundamentally different. Another reason why I think of this in floating target curve terms btw  rather than level offsets and a fixed curve position.

**Comment by aron7awol** [comment]
I get what you're saying and agree with it, but I guess I need to test more, because my results last night didn't seem to match up with my expectations based on everything we've talked about here so far.  My AVR was sending a way hotter signal than I expected based on everything I saw on the graph and myself assuming everything we've talk about was true.  The bass from the stereo track seemed roughly 10dB (I didn't have a reference to measure against) hotter than I expected, which led me to wonder if the tracks were treated differently, whether it was a boost to the stereo track's bass or a lack of attenuation that occurred with the surround tracks.

I have a really good sense at this point of what ULF components in that -15dB to -20dB band (~105-110dB at reference) on the graph feel like on my system, and what I was feeling from the stereo track was definitely way hotter than I expected, which doesn't make much sense considering the theoretical max of a stereo track, assuming everything we've discussed so far is true, would be 111dB.  Like I said, I'll just have to test more, something had to be off.  Maybe I can find some test tones that would be really good for this kind of testing.

**Comment by aron7awol** [comment]
One other piece of information is that I had Dolby Surround enabled to upmix the stereo source to my 7.1.4 setup.  Not that I would expect that to be boosting levels/bass, but I suppose I can't rule anything out.

**Comment by 3ll3d00d** [comment]
That changes everything then, your issue is one of how Dolby surround works on stereo sources

I would guess you could use the ffmpeg eac3 upmix to try to get some idea of how it works though I don't know how reliable this would be

**Comment by aron7awol** [comment]
You think Dolby Surround increases the volume of the track, or at least the bass?

Do you have any test tracks for WCS signals or any test tracks that you think would be valuable to test this particular issue?

**Comment by 3ll3d00d** [comment]
stereo playback with no further processing is simply stereo playback, there is nothing else going on (except bass management)

once you start upmixing then what you put in is not what you get out as it has to create/extract content to put into those other channels. I'd expect this to be equal energy at the low end though tbh. It would be odd if it weren't so I don't know what is going on. I suspect the most instructive thing would be to measure it but you need some real content to see what is really going on. I don't know that any particular track is better than another for this purpose.

**Comment by aron7awol** [comment]
I am running into another TV series in stereo, so I am going to re-visit this.

I created 3 test tracks to try tonight:
1. Stereo file with -3dBFS 20Hz sine wave in one channel, other channel silent
2. 5.1 file with -3dBFS 20Hz sine wave in one non-LFE channel, other channels silent
3. 5.1 file with -3dBFS 20Hz sine wave in LFE channel, other channels silent

If we assume bass management doesn't do anything different with stereo tracks, I think we would both expect the level of test tracks 1 and 2 to play back the same, and for test track 3 to play back 10dB louder.  Based on my previous experience in this thread, I am expecting track 1 to play back louder than track 2.  We'll find out tonight!

**Comment by 3ll3d00d** [comment]
Might be stating the obvious, and I don't know which processor you have, but presumably you will be using something like a direct mode that performs bass management with no further processing?

**Comment by aron7awol** [comment]
I will test direct mode, Dolby Surround upmixing mode, and regular stereo mode.  I really just want to fully understand what is happening, because what I previously experienced didn't seem to make sense.  My processor is a Denon AVR.

It seemed that perhaps when it was moving the content from the L and R channels to the sub channel, it was getting a +10dB bump like the LFE does.  That wouldn't actually make sense, but something seemed to be going on.

During my research of the issue, I found this old JRiver thread that seemed to be discussing a similar issue:
https://yabb.jriver.com/interact/index.php/topic,58646.0.html

**Comment by aron7awol** [comment]
These are the test tones I created for this purpose:
[testtones.zip](https://github.com/3ll3d00d/beqdesigner/files/2907281/testtones.zip)

**Comment by 3ll3d00d** [comment]
That is mostly about up or down mixing though isn't it? 2.0 is 2.0, it is not 2.1 (if you get what I mean).

**Comment by 3ll3d00d** [comment]
Also jriver's DSP has some questionable behaviour.  I can't say it is wrong because there is no published spec to say what it is intended to do, I can only say that the measured output of certain options seems a bit odd. I would be quite wary of using their bass management for example (reasons on the page I wrote on their wiki)

**Comment by aron7awol** [comment]
It seemed to be, at least initially, about how it handled bass management on a 2.0 source, which you might call "upmixing" to 2.1?  It was just something I came across while trying to research Dolby spec for expected behavior.  With Denon AVRs being so common, I consider this an important issue if it is in fact boosting the bass while moving it to the sub during bass management, so I figure I should spend the time investigating it.

**Comment by 3ll3d00d** [comment]
It is absolutely important to understand your own signal chain, no doubt about that :)

This is why I asked about direct though as I do not agree that bass management of 2.0 means turn it into 2.1, the .1 is the lfe channel and it either exists or not. Bass management is simply redirected bass and I expect redirected bass to simply be summed. Note that bass management has nothing to do with the .1 +10dB either (and yes I am pedantic!). Consumer electronics makes this into one black box but it is still a discrete series of operations.

**Comment by aron7awol** [comment]
I agree with you wholeheartedly!  In my mind, bass management and/or upmixing should always result in equal energy. I also agree with you and don't consider bass management to be the same thing as upmixing.  I would consider upmixing to be changing the channel layout before the processor, generally in the file or in the player, while bass management occurs in the processor.

So I think we are in complete agreement on everything and how it should be handled.  Now I just need to test and see if my Denon AVR is doing what we expect it to do.

**Comment by aron7awol** [comment]
As we would expect with proper behavior, the stereo and 5.1 track both played at the same volume, and the LFE track was 10dB higher.  So that's good.  Now I just need to go back and figure out what went wrong with Bodyguard.  I'll double-check everything I did to see if I can spot an error.

**Comment by aron7awol** [comment]
Actually, when testing Dolby Surround mode, I am seeing a small difference (~1db).  I will test it further with coherent sources in both stereo channels.
