### ISSUE TITLE
Error when trying to pull BEQ files from repo

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#209]
Unexpected Error detected, go to https://github.com/3ll3d00d/beqdesigner/issues/new to log the issue
Traceback (most recent call last): 
File "site-packages\git\__init__.py", line 83, in 
File "site-packages\git\__init__.py", line 73, in refresh 
File "site-packages\git\cmd.py", line 290, in refresh 
ImportError: Bad git executable. The git executable must be specified in one of the following ways: - be included in your $PATH - be set via $GIT_PYTHON_GIT_EXECUTABLE - explicitly set via git.refresh() All git commands will error until this is rectified. This initial warning can be silenced or aggravated in the future by setting the $GIT_PYTHON_REFRESH environment variable. Use one of the following values: - quiet|q|silence|s|none|n|0: for no warning or exception - warn|w|warning|1: for a printed warning - error|e|raise|r|2: for a raised exception Example: export GIT_PYTHON_REFRESH=quiet 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "model\preferences.py", line 598, in updateBeq 
File "model\preferences.py", line 609, in __clone_beq 
File "c:\users\mattk\anaconda3_64\envs\beq\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module 
File "site-packages\git\__init__.py", line 85, in 
ImportError: Failed to initialize: Bad git executable. The git executable must be specified in one of the following ways: - be included in your $PATH - be set via $GIT_PYTHON_GIT_EXECUTABLE - explicitly set via git.refresh() All git commands will error until this is rectified. This initial warning can be silenced or aggravated in the future by setting the $GIT_PYTHON_REFRESH environment variable. Use one of the following values: - quiet|q|silence|s|none|n|0: for no warning or exception - warn|w|warning|1: for a printed warning - error|e|raise|r|2: for a raised exception Example: export GIT_PYTHON_REFRESH=quiet

**Comment by 3ll3d00d** [comment]
Is that with the beta?

**Comment by aron7awol** [comment]
Yes, the latest release, beta2

**Comment by 3ll3d00d** [comment]
looks like gitpython has a dependency on git itself, will try to look for a pure python git impl (or include the git binary I guess)

**Comment by 3ll3d00d** [comment]
assuming you have git installed on this machine, the workaround will be to add git to your path
