### ISSUE TITLE
Previous BEQ filter not being cleared when loading new one.

### ISSUE THREAD

**Issue by Dolus01** [3ll3d00d/beqdesigner#212]
Hi 3ll3D00d
I noticed this afternoon that after using BEQ to remux a MKV file that if then loading a new BEQ filter the previous one is not cleared. The only option is to close then reopen the program.
Dolus

**Comment by 3ll3d00d** [comment]
thanks for the report

to delete a filter you just click on a row then click delete

![image](https://user-images.githubusercontent.com/2487509/52523112-b0cce000-2c85-11e9-9873-3c1275610084.png)
