### ISSUE TITLE
Adding more gridlines/labels to axis

### ISSUE THREAD

**Issue by richardsim7** [3ll3d00d/beqdesigner#215]
Would it be possible to add (be it permanently or by preference) more gridlines to the PvA and analysis graphs? 10Hz intervals, possibly even 5Hz?

**Comment by 3ll3d00d** [comment]
Similar to #24

**Comment by richardsim7** [comment]
Indeed, I figured since you worked out how to easily add more time intervals, then it shouldn't be too much of a leap to add more Hz ones too :)
