### ISSUE TITLE
Error when selecting signal in waveform view

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#230]
I don't know of anything different/special on this signal compared to any others, but I receive this error:

![image](https://user-images.githubusercontent.com/42757020/55255875-03605c80-5232-11e9-9ea3-12b258f83051.png)

**Comment by 3ll3d00d** [comment]
odd, it means the length of the track changed by 1 sample. The particular line of code it has blown up suggests a rounding error in calculating the signal duration (plausible as you have to convert to/from no of samples).

**Comment by 3ll3d00d** [comment]
I'd probably need the actual audio file to dig into it (if it's not too big to share)

**Comment by aron7awol** [comment]
I'm pretty sure it was the Spider-Man 3 Atmos track.  I'll test it again to make sure, and then send it over it it is.  Do you need the original track or can I decimate and mix it to mono before I share?

**Comment by aron7awol** [comment]
[Spider-Man.3.2007.2160p.UHD.BluRay.x265-DEPTH_s1_custom_to_mono.wav.zip](https://github.com/3ll3d00d/beqdesigner/files/3040936/Spider-Man.3.2007.2160p.UHD.BluRay.x265-DEPTH_s1_custom_to_mono.wav.zip)
