### ISSUE TITLE
feature request: drag and drop file to Extract Audio dialog box to populate path

### ISSUE THREAD

**Issue by richardsim7** [3ll3d00d/beqdesigner#233]

**Comment by 3ll3d00d** [comment]
I did have a look at this and it seems that there is no obvious built in Qt droparea widget instead most (all?) Qt widgets have support for such an event handler so are droppable. This is both handy (anything can be a drop area) and annoying (it will take longer to work out how to do it)!

**Comment by richardsim7** [comment]
Yay! I think...

I guess the whole Extract Audio as droppable would be nice, and it just fills that one field

**Comment by richardsim7** [comment]
Doesn't appear to be working in Windows 10 x64 v1809
v0.7.0 b7

**Comment by 3ll3d00d** [comment]
Are you dragging to the right location? The area to the right of the text field

**Comment by richardsim7** [comment]
Yup, same result anywhere on that window

**Comment by 3ll3d00d** [comment]
works for me (on Windows 10)
