### ISSUE TITLE
the minidsp xml files are incorrect for the fixed point hardware

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#240]
example provided by @bmiller 

actual values

```
<dec>1.0001700271684784,-1.9983741385794638,0.9982087694955691,1.9983748747 626051,-0.9983780604809058,</dec>
<hex>00800592,0f003546,007fc54e,00ffcabf,0f803525, </hex> 
```

this does not match the currently generated values

**Comment by 3ll3d00d** [comment]
the minidsp fixed point hardware uses Q5.23 format (as per p15 of http://datasheet.digchip.com/041/041-21660-ADAU1701.pdf) 

the hex values should be calculated as

```
>>> m=5
>>> n=23
>>> a=1.0
>>> hex(int(a*(2**n)))
'0x800000'
>>> a=1.0001700271684784
>>> hex(int(a*(2**n)))
'0x800592'
```

**Comment by bmiller** [comment]
Hey, I played with this a little bit.  The following will give correct results but I'm not sure if theres's a better way to do it.  The negative numbers were the main issue from what you posted.  Making them positive and then doing an xor on the int with 0xfffffff produces the same values as the save files. 

`def float_to_28hex(f, minidsp_style ):
    '''
    Converts a floating number to its 28bit  hex representation.
    :param f: the float.
    :param minidsp_style: if true, don't print 0x prefix.
    :return: the hex value.
    '''
    isNeg = False

    if f < 0:
        isNeg = True
        f = f * -1

    n = 23
    intValue = int(f*(2**n))

    if isNeg:
        intValue = intValue ^ 268435455

    value = struct.unpack('<I', struct.pack('<i', intValue))[0]
    return f"{value:{'#' if minidsp_style is True else ''}010x}"`

**Comment by 3ll3d00d** [comment]
I believe that is the correct way to do it

**Comment by bmiller** [comment]
ok, cool.  I wasn't sure if there was a better/easier way in python for it.  I don't know the corners of it well enough to know if there's some library or something that would take care of the 2s complement.  

I saw the commit you did and it looks good.
