### ISSUE TITLE
Make the Preferences window scrollable

### ISSUE THREAD

**Issue by bmiller** [3ll3d00d/beqdesigner#242]
PioManiac ran into an issue tonight where the prefs window was larger than his screen.  It should probably be made scrollable and resizable for smaller screen sizes.

**Comment by 3ll3d00d** [comment]
that window is rendering curiously large on Windows though it was only approximately 800 px square. I guess he must have a 768px tall screen which is a bit small.

**Comment by bmiller** [comment]
yeah, he's running 1366x768.  I was surprised at his resolution for the 15.6" laptop.  I'm used to my two 15" MBPs which are much higher resolution.
