### ISSUE TITLE
miniDSP merge missing filter

### ISSUE THREAD

**Issue by bmiller** [3ll3d00d/beqdesigner#245]
It looks like there's an off by one error somewhere in the filters.  The files being produced are missing the '<filter addr="y" name="PEQ_x_10">' for the 2x4 HD and '<filter addr="y" name="PEQ_x_6">' for the other options.  

Not having them is causing the plugin to hang when trying to load them.  Manually adding them back to one of the files resulted in it loading correctly.

**Comment by 3ll3d00d** [comment]
I was actually just fixing this myself :)

I got hold of the minidsp ui exe so was trying it out so noticed this while also diff'ing some files
