### ISSUE TITLE
Automated build issue

### ISSUE THREAD

**Issue by bmiller** [3ll3d00d/beqdesigner#253]
I'm assuming this is on all builds but I've only tested on the Mac build.  It looks like the build happened before my commit to the 10x10 merge issue was applied.  The build is creating files with the hex values containing 0x prefix and either 24 or 28 bit values still. 

Could you trigger the build again so that we can check that it was simply that the builds were done before the PR merge and not an issue with the automated build process?  I'm assuming it's pulling master when it run.  

Thanks!

**Comment by 3ll3d00d** [comment]
builds are published off the tag and it gets the code as follows

```
git clone --depth=50 --branch=0.7.0-beta.1 https://github.com/3ll3d00d/beqdesigner.git somedir
cd somedir
git checkout -qf 0.7.0-beta.1
```

this shows your commit is in the source

**Comment by 3ll3d00d** [comment]
I also compared running it off master vs the published exe and they both produce the same output as far as I can see

can you give an example of what it is producing vs what it should be?

**Comment by 3ll3d00d** [comment]
btw see https://www.avsforum.com/forum/113-subwoofers-bass-transducers/2995212-bass-eq-filtered-movies.html#post57961588

**Comment by bmiller** [comment]
Sorry, you posted this right after I went to bed.  Time differences suck some times.  It looks like you found a sample file in Slack.  I also invited you to the dev channel on it that has more info and sample files in it.  

This started last night because of Nalleh messaging that the build I posted for him on slack worked correctly but the automated build gave him an error.  When I ran the automated build, the hex values for the 10x10 looked like:
<hex>0x80095e,0xf004488,0x7fb254,0xffbb83,0xf804458,</hex>

After the change I submitted it should be:
<hex>0080095e,0f004488,007fb254,0ffbb83,0f804458,</hex>

I have a comment in the code for it.  With testing with Nalleh we found that the 0x prefix caused there to be no sound with the 10x10. Then not having it padded to 32 bits caused a feedback loop for him. The fix for it was in iir.py and looking at the repo it's still there.  We didn't have a merge issue.  So that along with it working in the build I manually made lead me to believe the automated build happened before it.  

For the 2x4 non-HD files, that's a new one to me.  I've been seen the files for one.  I had asked to be sent them and the guy that said he had one never sent a file.  Since there's been no complaints about it not working I figured that either it was working or no one was using it.  From the post you made today it looks like their file is like another version of it.  It'd be nice if miniDSP could be consistent.

**Comment by 3ll3d00d** [comment]
it seems ok in all the builds I've tried

fwiw I've added a way to see these values are more quickly by allowing the biquad export page to show you the hex values for a given minidsp type

![image](https://user-images.githubusercontent.com/2487509/56854416-257ef480-692e-11e9-97d5-619f45f7f620.png)

probably helps debug such issues more quickly
