### ISSUE TITLE
Can the peak spectrum be saved without re-rendering?

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#255]
I don't change the pixel sizing of the peak spectrum when I save it, so I was wondering if the peak spectrum already displayed on the screen could be saved straight from that rendering rather than what seems to be happening, which is a full re-render before saving as a PNG.

**Comment by 3ll3d00d** [comment]
no there's no way around this, it's just how matplotlib works

matplotlib has a plotting engine which lets you describe different figures and then a rendering engine which has many different [backends](https://matplotlib.org/tutorials/introductory/usage.html#backends) for rendering to different formats. 

In this particular case, we are rendering once to a Qt widget (the thing you see on the screen) and then again to a png file.
