### ISSUE TITLE
Use standard shortcuts for saving a project

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#260]
1. Ctrl-S is currently a shortcut to save the chart and Ctrl-R is to save report.  I use the Ctrl-R shortcut often, but I sometimes accidentally hit Ctrl-S to save the project since that is a standard shortcut in many apps.  I understand if you want to leave Ctrl-S as save chart since that is what it has been for a while, but can you add a shortcut for Save Project?

2. When the user clicks the small up arrow button to bring up the waveform view, if there is only one signal loaded, can you make the Signal dropdown default to it?  If there is only one signal loaded and the user clicks that button, I think it is safe to assume they want that one selected for the waveform view.

**Comment by 3ll3d00d** [comment]
> 2\. When the user clicks the small up arrow button to bring up the waveform view, if there is only one signal loaded, can you make the Signal dropdown default to it?  If there is only one signal loaded and the user clicks that button, I think it is safe to assume they want that one selected for the waveform view.

will break this out to a separate issue
