### ISSUE TITLE
If a single signal is loaded, default the waveform view to that signal

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#261]
> 2\. When the user clicks the small up arrow button to bring up the waveform view, if there is only one signal loaded, can you make the Signal dropdown default to it?  If there is only one signal loaded and the user clicks that button, I think it is safe to assume they want that one selected for the waveform view.

_Originally posted by @aron7awol in https://github.com/3ll3d00d/beqdesigner/issues/260

**Comment by 3ll3d00d** [comment]
@aron7awol this one needs a bit more work because it makes you select something to look at atm in order to avoid any chance it sits there computing the effects of a filter on a waveform you can't see, easily avoided but requires a bit of a more thorough check through the code

**Comment by aron7awol** [comment]
I thought that by having this default selection happen only when the user clicks the little up arrow button which shows the waveform view, it would avoid that sort of thing from happening.  But I realize I'm probably not thinking of something :)

**Comment by 3ll3d00d** [comment]
yes that should work but I think I bodged something in in the past to add an extra guard against doing work for things offscreen that means some other bits need unpicking/rewiring, just some mess in code basically that probably takes me 20-30mins to work through

**Comment by 3ll3d00d** [comment]
this probably needs refining a little bit so that it shows the selected signal in the waveform view unless the user has explicitly picked a waveform to look at
