### ISSUE TITLE
Add miniDSP nanoAVR merge support

### ISSUE THREAD

**Issue by bmiller** [3ll3d00d/beqdesigner#271]
Add support for the nanoAVR.  It looks straight forward like the other miniDSP except that the gain needs to be adjusted.  I was going to look to add support when I have a few minutes for it.  

raynist sent me the plugin through drop box if you want to take a look at it.  I'm not sure if it's shared publicly or just with me.  I'll put it up somewhere if this link isn't accessible .

https://www.dropbox.com/l/scl/AABkFzbutcHK22ZA4hjuytX9Wxa9-xfR_vg

**Comment by 3ll3d00d** [comment]
I can't access it

**Comment by bmiller** [comment]
This one should work.  I copied it to my dropbox and made it public.
https://www.dropbox.com/s/zlulc2nz6gdnwgu/nanoAVR_BM_112.zip?dl=0

raynist latest post sounds like it's not needed now.  We could still add it to have coverage but I'm not sure anyone would be using it.

**Comment by bmiller** [comment]
Just noticed this one was still open.  Closing since the person who asked for it went with a different unit.  No one else has asked for it or uses one as far as I know.
