### ISSUE TITLE
Support for Merging User Defined BEQ files

### ISSUE THREAD

**Issue by mtnwatchdog** [3ll3d00d/beqdesigner#273]
Allow users to extend upon the "Merge MiniDSP XML" process with their own BEQ xml source directory containing additional movies not in the primary community set. This directory could be processed following the primary file set, similarly merging the user's house curve, and storing into the same Output Directory.

**Comment by 3ll3d00d** [comment]
@mtnwatchdog this will be in 0.7.3-beta.2
