### ISSUE TITLE
Request: add 5Hz lines to spectrum graphs

### ISSUE THREAD

**Issue by richardsim7** [3ll3d00d/beqdesigner#274]
Any chance we could add the same 5Hz lines that were added to the PvA graphs, to the spectrum ones too?

**Comment by richardsim7** [comment]
Or rather, add 10Hz lines so it closer matches the PvA graphs, see mismatch here, for example: https://i.imgur.com/09WF5es.jpg

**Comment by 3ll3d00d** [comment]
It is never going to match up exactly, if that is what you mean then not much point changing it. It also gets quite busy when doing side by side view.

**Comment by richardsim7** [comment]
Nah I'm not expecting it to line up when they're stacked, I just meant it's odd having 10Hz lines on the top graph and only 20Hz ones on the bottom
