### ISSUE TITLE
Does headroom calculation work properly with HPF?

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#275]
I loaded the War of the Worlds mixed-to-mono signal and headroom shows as 4.56dB.  I tried applying a bunch of different HPFs to it and headroom **decreased** significantly, and it decreased more with higher order and higher frequency.  I know that adding a HPF changes phase, so it may in fact be working correctly and it just so happens to reduce headroom in this case, but I just want to double-check because it seems to be consistently decreasing headroom while I would expect phase changes to have a more random effect, and I expected the filter response to increase headroom significantly, more than the phase changes would.  I haven't done a lot of testing, so it might just be a coincidence, but I thought you'd be able to add some insight.

**Comment by 3ll3d00d** [comment]
Decreased headroom means it moved towards 0 right?

The phase effects on headroom are consistently counterintuitive though in general so the above does not surprise me. Try adding a lpf as well and see if that helps you out.
