### ISSUE TITLE
Disable DRC in the extract audio command line

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#277]
Adding

-drc_scale 0

to the command seems to do the trick!

**Comment by 3ll3d00d** [comment]
what command did you use exactly?

**Comment by aron7awol** [comment]
I've been copying your generated command and just adding -drc_scale 0 right after ffmpeg:

ffmpeg -drc_scale 0 -i...

**Comment by 3ll3d00d** [comment]
ok that's what I did

I was just trying to find some evidence that it was making any difference, nothing in the generated output and the files I've tried so far seem identical. I guess that means they don't have such metadata.

**Comment by 3ll3d00d** [comment]
actually it reports that output when the stream is not AC3 so that must mean it is doing something

**Comment by aron7awol** [comment]
Remember the issue I posted a while back about the level of a stereo track being much hotter than expected based on the graph?  I have a feeling now that track had DRC metadata too and that is the explanation.

It seems like a somewhat strange choice of the ffmpeg developers to default DRC to on.

**Comment by 3ll3d00d** [comment]
added in https://github.com/3ll3d00d/beqdesigner/commit/e51899d1c78781acab52324f901dbcb1264dcf17
