### ISSUE TITLE
Cannot add more than 6 signals

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#28]
![image](https://user-images.githubusercontent.com/42757020/45060513-1fba6300-b06e-11e8-8126-17b5bf0ef99d.png)

**Comment by 3ll3d00d** [comment]
5.1 is the limit I guess 😁 

Is this using the latest build (0.0.2-beta.2)?

**Comment by aron7awol** [comment]
Yes.

**Comment by aron7awol** [comment]
I think the colors of the lines start to repeat after 4 also, but that was a minor issue I was willing to deal with since I didn't really need to differentiate individual episodes in this case.  Then when I got to the 7th it crashed.

**Comment by 3ll3d00d** [comment]
It is probably the colour picker then. There are only so many distinguishable shades of green and red so it is going to repeat if it sticks with those colours. An alternative would be to let the colours vary beyond red/green and use linestyle to denote peak/avg but then everyone will be like "what's going on with the graphs" :)

I imagine the graph is unreadable with too many curves anyway. Perhaps limiting it to 8 is reasonable (i.e. a 7.1 track) or should leave it unbounded and let the colours repeat?

**Comment by aron7awol** [comment]
I would prefer if you did not limit it and let them repeat.

**Comment by 3ll3d00d** [comment]
I could do that but useability is horrible because there are so many lines on the graph and the colours are all so similar.

**Comment by 3ll3d00d** [comment]
The next release ups the limit to 10 and removes the error. This seems plenty to me given the useability issue of so many similarly coloured lines.

What are you doing that needs more than 10? If there is a common use case then I can think about colour schemes to support that.

**Comment by aron7awol** [comment]
The only reason I would like more than 10 is I'd like to BEQ entire seasons of a show with one set of filters.  In that use case, actually differentiating between different signals is unnecessary as it's only to show that it works for all of them, so the colors don't really matter at all.
