### ISSUE TITLE
Add uploading to Imgur for PvA and Spectrum

### ISSUE THREAD

**Issue by bmiller** [3ll3d00d/beqdesigner#283]
Aron asked if it would be possible to add uploading of the graphs to imgur for him.  It looks like they have an API to do it.  If we add this in a nice to have would be to store the 2 URLs along with the signal/filters to auto populate the AVS post builder.

**Comment by 3ll3d00d** [comment]
this was previously logged as #64 

I eventually closed it as I have no intention of doing this given how little time is saved vs how much effort is involved in the app to get it done, doesn't seem worthwhile to me and opens up the maintenance surface (no idea how stable the imgur api is) hence still not particularly keen on it

**Comment by bmiller** [comment]
Sorry, I didn't see #64 when I looked.  I'm fine with not adding it.  It felt a little odd workflow wise to me.  Aron had asked though so I figured I'd bring it up.

**Comment by bmiller** [comment]
Duplicate of #64
