### ISSUE TITLE
Median line necessitates more vertical gridlines

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#287]
Since showing the median line requires a wider range of levels on the vertical scale, the gridlines every 5dB disappear, leaving 10dB increments only.  I think people will want to see the 5dB increments on that axis.

**Comment by 3ll3d00d** [comment]
I have a feeling this is going to be tricky to do without producing too many lines in other situations

it's also a lot of lines anyway as the median is often much lower in level, not sure there is going to be a nice way to maintain the range and stick to 5dB ticks

**Comment by aron7awol** [comment]
Which other situations do you think it will produce too many lines?

I was thinking something like
max = 24, steps = [1,5,10]

max of 24 is working well on the peak spectrum.

**Comment by 3ll3d00d** [comment]
I was thinking of how it will react with smaller ranges, for example 30dB range in the above will yield 5dB steps which is not enough so you have to add 2 to that list. I was then concerned that it would step down to 2 too soon but actually it will still be at 5 with 60dB range (and keeps at that till 120dB range which should be plenty).

**Comment by 3ll3d00d** [comment]
I used `MaxNLocator(nbins=24, steps=[1, 2, 5, 10], min_n_ticks=8)` so lets see how that works
