### ISSUE TITLE
System cannot find file specified

### ISSUE THREAD

**Issue by richardsim7** [3ll3d00d/beqdesigner#29]
App version:  0.0.2-beta.2

**Window title: Unexpected Error**
Traceback (most recent call last): 
File "model\extract.py", line 57, in selectFile 
File "model\extract.py", line 86, in __probe_file 
File "site-packages\ffmpeg\_probe.py", line 16, in probe 
File "subprocess.py", line 709, in __init__ 
File "subprocess.py", line 997, in _execute_child 
FileNotFoundError: [WinError 2] The system cannot find the file specified

Using the extract tool, I selected an mkv that is on a network share, wondering if this is the cause of the error

Scratch that, tried copying the file to a local directory and got the same error

Seems to happen with any mkv

Launching app as admin didn't help either

Windows 10 Pro x64 v1803

**Comment by 3ll3d00d** [comment]
You need to tell it where the ffmpeg binary is (or have them on your path). See the preferences dialog for where you enter this.

**Comment by richardsim7** [comment]
Yup, I read the wrong set of instructions, that fixed it :)

Small request: potentially add a progress bar for extracting audio? Otherwise it just looks like the app freezes whilst it works

**Comment by 3ll3d00d** [comment]
Not currently possible without hacking the ffmpeg wrapper I use, see https://github.com/kkroening/ffmpeg-python/issues/43 for details
