### ISSUE TITLE
Qt error when editing filter

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#292]
hmm I tried it on another machine and see the error is

    <class 'SystemError'> <built-in function connectSlotsByName> returned a result with an error set <traceback object at 0x0000000A461DD688>�

so something in Qt is blowing up

_Originally posted by @3ll3d00d in https://github.com/3ll3d00d/beqdesigner/issues/285#issuecomment-513583625_

**Comment by 3ll3d00d** [comment]
seems similar to https://github.com/tohojo/flent/issues/167 and in the same circumstances in that it occurs when you go beyond pyqt5 5.12.1 

i.e. seems like it must be a pyqt5 bug

**Comment by bmiller** [comment]
Can we just lock the pipfile to pyqt5 5.12.1 then for the time being?

**Comment by 3ll3d00d** [comment]
this introduces some other errors, I'm not going to pin to a variety of old versions of things so will have to work through the build issues

**Comment by 3ll3d00d** [comment]
seems to be fixed in https://github.com/3ll3d00d/beqdesigner/releases/download/0.7.3-beta.12/beqdesigner.exe (though still broken in beqdesigner_small.exe)
