### ISSUE TITLE
0.7.3-beta.14 launches but error when adding second filter

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#301]
Using the large exe, it launches fine, added a signal, added a filter.  Went to add a second filter and received this error:

`Unexpected Error detected, go to https://github.com/3ll3d00d/beqdesigner/issues/new to log the issue
AttributeError: __getattribute__ 
The above exception was the direct cause of the following exception: 
Traceback (most recent call last): 
File "app.py", line 575, in addFilter 
File "model\filter.py", line 249, in __init__ 
File "ui\filter.py", line 174, in setupUi 
SystemError: returned a result with an error set `

**Comment by 3ll3d00d** [comment]
Give beta.15 a try
