### ISSUE TITLE
Hide median on report?

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#303]
After viewing the median line on a bunch of BEQs, I have to say that unfortunately it doesn't seem to be adding value.  I think the biggest issue is that it is too easily affected by noise, even lower-level non-detrimental noise.  I've tried to find value in it when designing, as I was hoping it would act as an additional guide, so to speak, in between peeks at the peak spectrum during design.

I don't mind keeping it there during design and I'll just see if I can eventually find some use for it, but I don't want to include it in the published reports because it's all over the place, forces the use of a much larger vertical axis range, and I think it will just cause confusion for some people who haven't seen it, without adding anything positive that I can see.

I know you spent some work adding it, which is of course appreciated, and maybe others can find value in it somehow, so I'm not suggesting you remove it completely, but it always shows up by default on each report I generate and I have to manually remove the median lines each time.  This is even worse on TV series, as each signal has two lines that need to be manually removed.  So I'd like to see a way to default it to not show on the report.

**Comment by 3ll3d00d** [comment]
probably should honour the selected view on the main screen

**Comment by 3ll3d00d** [comment]
should be in 0.9.0-beta.3 in the next 20-30mins
