### ISSUE TITLE
List Index Out Of Range Errors

### ISSUE THREAD

**Issue by Mobe1969** [3ll3d00d/beqdesigner#306]
I've had this issue since upgrading to the latest version. I then tried the beta and got the same issue.
0.9.0-beta.4 and initially 0.7.3 final, windows installer.

When I load a signal, either a pre-existing one I'd used before, or processed a new video file to create a mono and signal, no graph shows, and when I try look at the Eye button next to the Smoothing / All Signals, it shows this error:

```
Traceback (most recent call last): 
File "app.py", line 844, in showValues 
File "model\magnitude.py", line 218, in show_values 
File "model\limits.py", line 247, in __init__ 
File "model\limits.py", line 277, in __interpolate_data 
IndexError: list index out of range 
```

**Comment by Mobe1969** [comment]
Here is a sample signal file, one I just created.

[Colombiana_s1_5.zip](https://github.com/3ll3d00d/beqdesigner/files/3537594/Colombiana_s1_5.zip)

**Comment by Mobe1969** [comment]
Screenshot
![beq](https://user-images.githubusercontent.com/46695255/63643054-9f709000-c70c-11e9-9195-52c23d2e34a9.PNG)

**Comment by 3ll3d00d** [comment]
this opens normally for me, which version is this again? which OS?

**Comment by 3ll3d00d** [comment]
also are you using the _small exe or the other one?

**Comment by 3ll3d00d** [comment]
can't reproduce this using either windows exe (for 0.9.0-beta.4)

**Comment by Mobe1969** [comment]
I'm using the installers. What is the difference with the others? Why the size difference?

**Comment by Mobe1969** [comment]
BTW, I installed 0.7.2 (small installer) and it worked first time. I'll try stepping through versions to figure which one I get to before it stops.

**Comment by 3ll3d00d** [comment]
There aren't any prerequisites as it is a completely self contained exe. I don't know why it would behave differently on your machine tbh.

**Comment by 3ll3d00d** [comment]
> I'm using the installers. What is the difference with the others? Why the size difference?

the exe basically behaves like a zip in that it first extracts everything to some tmp dir and then runs the app, the setup just extracts everything to an install directory up front. This means it is exactly the same except quicker to start.

size difference is because one exe uses anaconda python and the other one uses python.org, anaconda numpy/scipy ship with intel [MKL](https://software.intel.com/en-us/mkl) DLLs and those are some pretty big DLLs. There is no noticeable performance impact either way so I was attempting to cut over to python.org on size grounds. However there has been some flakiness in the different builds so I've kept them both around.

**Comment by Mobe1969** [comment]
I've tried two other machines, different OS versions, same result, so not just my machine.

I do have 0.7.2 installed now, and it works. The only issue I'm noticing still I had before was in the spectrum view, the Resolution dropdown is always empty.
![image](https://user-images.githubusercontent.com/46695255/63714705-aff84600-c885-11e9-8a00-f0eb4438ce6d.png)

What OS are you using?

I won der if it is something MKL releated then?

**Comment by Mobe1969** [comment]
BTW, I just spooled up a brand spanking new win 10 Pro VM, same result.

I'll have to try getting a dev environment working and try tracing it.

**Comment by Mobe1969** [comment]
I've tried setting up a development environment in windows but haven't gotten it running yet.

Regards the versions, I've been installing versions above mine to find specifically when it stopped working and maybe see what code changed and:
0.7.3 Beta 2 - works
0.7.3 Beta 3 - this version won't run at all in windows. Errors show in the command window and it disappears so I'm not sure what.
0.7.3 Beta 4 - this version won't run at all in windows
0.7.3 Beta 5 - this version runs, but the List Index out of range starts occurring and no signal shows

**Comment by Mobe1969** [comment]
Oh gee, I think I figured what it was- the Average/Peak combo box down at the bottom right. It was set to all. As soon as I set it to just Peak and Average, it doesn't crash anymore, and shows the signal!

**Comment by 3ll3d00d** [comment]
good sleuthing :1st_place_medal: 

funnily enough I had been thinking recently "this must be a config error somewhere" and so it was
