### ISSUE TITLE
FLAC Signal Error

### ISSUE THREAD

**Issue by LLuth0r** [3ll3d00d/beqdesigner#308]
Issue when creating signals from FLAC extraction of a full length movie.  Mix to Mono unchecked, Decimate Audio checked.  Any full length movie gives me this issue (6GB+).  It will create the FLAC file, but as soon as I try to create the signals from that file, it gives the attached error.  The file size for this particular file is an 8GB MKV.   

![BEQD Extract Details](https://user-images.githubusercontent.com/50471818/64340850-1d5a5400-cfb5-11e9-824c-5a150503a9af.PNG)
![BEQD Error](https://user-images.githubusercontent.com/50471818/64287215-1c7ddf80-cf2d-11e9-854b-fafc2f923594.PNG)

**Comment by 3ll3d00d** [comment]
Which version are you running?

**Comment by LLuth0r** [comment]
I've got the v0.9.0-beta.4 on my work PC, which is what I used to log this issue.  On my home machine I'm running the latest final build, 0.7.3, and it gives me the same error.  Downloaded and installed the small setup, 0.7.3, on my work computer just now to try it and I got the same error.

**Comment by 3ll3d00d** [comment]
it appears that the underlying library (libsndfile) reads no data from a 1000Hz multichannel flac file, I have no idea why and I don't recall ever testing this. The reason being that there is no point (that I'm aware of) using flac for a decimated track as the wav will be small anyway. 

The existence of a valid workaround (use wav not flac for this use case) & the fact the issue is in a 3rd party library means it's unlikely I'm going to spend much time looking into this.

**Comment by LLuth0r** [comment]
Thanks for responding Matt.  For remuxing, is there any point in decimating
the audio since I’m trying to preserve as much info as possible?

Mike

**Comment by 3ll3d00d** [comment]
having said that, it seems to happen with tracks that aren't decimated either and that definitely used to work. I'll take a look further at this when I get the chance.

**Comment by 3ll3d00d** [comment]
The one and only reason to decimate is to make BEQ design less resource intensive which means signals are quicker to load, filters are quicker to apply and so on. This works fine as BEQ is focused on the overall shape of the signal <100Hz (or even <50Hz). If you want to see an accurate view of the full range signal then don't decimate.

**Comment by LLuth0r** [comment]
Ah ok, makes sense.  Thanks again for your help.  I’ll just continue to
utilize the wav extraction with decimate.

Appreciate all you’ve done and love following along the BEQ AVS thread.

Mike

**Comment by 3ll3d00d** [comment]
appears to be the same problem as noted in https://github.com/bastibe/SoundFile/issues/236

**Comment by 3ll3d00d** [comment]
Which sounds like https://github.com/erikd/libsndfile/issues/431

**Comment by 3ll3d00d** [comment]
fix should arrive in 0.9.0-beta.6
