### ISSUE TITLE
Add a peak signal by Freq timestamp report

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#32]
i.e. report the time periods that contain the peak frequencies

**Comment by aron7awol** [comment]
I like this idea a lot.  Could you also report the time periods that contain the top X peaks of the overall waveform as well?

**Comment by 3ll3d00d** [comment]
1st pass at this implemented by #39

**Comment by 3ll3d00d** [comment]
closing on the grounds of having done something in the vicinity of this request
