### ISSUE TITLE
Support for Minidsp 88a-bm

### ISSUE THREAD

**Issue by tabbycph** [3ll3d00d/beqdesigner#361]
Hi, support for 88a-bm will be really superb, here is the files for 21 bridges, that I saved from the Minidsp 88a-bm
[21_Bridges_88a-bm.zip](https://github.com/3ll3d00d/beqdesigner/files/4524828/21_Bridges_88a-bm.zip)

**Comment by 3ll3d00d** [comment]
#364 will allow selection of the output channel for the filters, atm it is hardcoded to channel 3
