### ISSUE TITLE
Please add support for minidsp SHD

### ISSUE THREAD

**Issue by mitch236** [3ll3d00d/beqdesigner#363]
I would like to request support for the minidsp SHD.  I tried to add an export file but it won't let me attach it.  I'll try to pm it to you through avs

Thanks!
Mitch

**Comment by mitch236** [comment]
If you go to https://github.com/mitch236/beq-xml you will find the Blade Runner XML export

**Comment by 3ll3d00d** [comment]
commented https://www.avsforum.com/forum/113-subwoofers-bass-transducers/2995212-bass-eq-filtered-movies.html#post59617324

device is missing input PEQ which is where BEQ filters go on the 2x4HD

**Comment by mitch236** [comment]
I've updated the GitHub to include Blade Runner SHD

[https://github.com/mitch236/beq-xml](url)
