### ISSUE TITLE
Minor UI suggestions/requests

### ISSUE THREAD

**Issue by Alex1238** [3ll3d00d/beqdesigner#379]
(These are not relevant to the main functions of BEQdesigner so can be given low priority).

1.) After loading a BEW .xml file, nowhere on the interface does it confirm the name of the .xml file I just loaded.  Using BEQs as often as I do it's plausible I'll click on the wrong file 1% of the time.  Can the name of the currently loaded .xml be displayed somewhere on the interface, anywhere? Appended to the title bar even?

2.) When exporting Biquad to Equalizer APO format, could the name of the .xml file be also prepended to the filter text with a #? E.g like this:
```
# Constantine (2005) (+1 gain) BEQ TrueHD 5.1
Filter 1: ON LSC Fc 10 Hz Gain 5 dB Q 0.9
Filter 2: ON PK Fc 20 Hz Gain 6 dB Q 3.5
```

3.) When copying the filters from the Export Biquad window, if I close BEQdesigner before pasting the filter, the text gets removed from the clipboard.  Text from most applications is able to persist on on the clipboard after the application is closed, can BEQdesigner do this too?

Thanks.

**Comment by Alex1238** [comment]
Example for no2 didn't format correct because of the "#".  I meant it to look like this but without the quotes.

"# Constantine (2005) (+1 gain) BEQ TrueHD 5.1
Filter 1: ON LSC Fc 10 Hz Gain 5 dB Q 0.9
Filter 2: ON PK Fc 20 Hz Gain 6 dB Q 3.5"

**Comment by 3ll3d00d** [comment]
@Alex1238 re 3, which OS are you using? the data is retained by the clipboard after exit on each OS I've tried (Windows 8.1, linux running KDE). As far as I know, this is not something my app controls so it's left to the OS to decide whether something stays in the clipboard or not.

**Comment by 3ll3d00d** [comment]
implemented 1 & 2 in 0.9.5-beta.11
can't reproduce 3

**Comment by 3ll3d00d** [comment]
clipboard issue might possibly be https://bugreports.qt.io/browse/QTBUG-11616 but I can't reproduce it so it is bit tricky for me to try to workaround it, I suppose the solution is not to exit beqdesigner before you've pasted that somewhere

**Comment by Alex1238** [comment]
Much appreciated for implementing 1 & 2.

I'm still using Windows 7 (I know...).  Thanks for looking into no.3.  Keep up the great work.
