### ISSUE TITLE
Fix conda/venv incompatibility

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#387]
fix suggested in https://github.com/ContinuumIO/anaconda-issues/issues/10822 is downgrading venv to 20.0.33

**Comment by whg517** [comment]
hello , i have same issue.

- vmWare install windows
- os: 10.0.19041 暂缺 Build 19041
- conda: Miniconda3-py37_4.8.3-Windows-x86_64.exe
- virtualenv: 20.1.0
- pipenv: 2020.11.15

when i run `pipenv install ` or `virtualenv venv` , it's error.

```
PS C:\Users\test\AppData\Local\Temp\test> pipenv install
Creating a virtualenv for this project...
Pipfile: C:\Users\test\AppData\Local\Temp\test\Pipfile
Using C:/ProgramData/Miniconda3/python.exe (3.7.7) to create virtualenv...
[  ==] Creating virtual environment...FileNotFoundError: [Errno 2] No such file or directory: 'c:\\programdata\\miniconda3\\Lib\\venv\\scripts\\nt\\python.exe'

Failed creating virtual environment

[pipenv.exceptions.VirtualenvCreationException]:
Failed to create virtual environment.
```

**Comment by 3ll3d00d** [comment]
no longer using conda after #396
