### ISSUE TITLE
App doesn't see ffmpeg and ffprobe binaries (OSX)

### ISSUE THREAD

**Issue by olegkurchin** [3ll3d00d/beqdesigner#390]
After fresh install, app seems not to recognize ffmpeg and ffprobe binaries correct, when trying to set the path with Preferences > Binaries menu. Binaries items **remain grayed-out** (be it downloaded from ffmpeg.org or Zeranoe)

<img width="619" alt="Screenshot 2020-12-01 at 00 43 54" src="https://user-images.githubusercontent.com/5749140/100672295-c6d3f500-3372-11eb-822e-c5d8944e0b31.png">

OSX Mojave 10.14.6

PS. 'homebrew install ffmpeg' works so far, while installs ffmpeg into system directory

**Comment by 3ll3d00d** [comment]
looks like a os specific bug, code is actually looking for `ffmpeg.exe` so is broken on Linux too (for which I always just have system ffmpeg hence never noticed it). Thanks for reporting.

**Comment by 3ll3d00d** [comment]
fixed in latest beta

**Comment by olegkurchin** [comment]
Great! Thanks a lot
