### ISSUE TITLE
AC3 support for compatibility with older receivers

### ISSUE THREAD

**Issue by olegkurchin** [3ll3d00d/beqdesigner#392]
Some older AVRs don't support E-AC3, working improperly. Until then, there is a workaround, for those interested. Once remux, use
`ffmpeg -i input.mkv -map 0:v -map 0:a:0 -c copy -c:a ac3 -b:a 640K output.mkv`

where 
1) input.mkv - name of remuxed file
2) output.mkv - name of file encoded into ac3
3) example assumes that the target soundtrack is the 1st one (hence 0: a :0 - ffmpeg starts count from 0)
4) 640K seems to be the largest audio bitrate, acceptable for ac3 (lower number may be used, any greater will set to default 640)

**Comment by 3ll3d00d** [comment]
included in 0.9.7-beta.1
