### ISSUE TITLE
Unexpected error message when attempting to extract audio

### ISSUE THREAD

**Issue by rexxyic4** [3ll3d00d/beqdesigner#395]
Hi, firstly thank you very much for creating this excellent tool.

I'm new to BEQ and BEQdesigner.  I attempted to extract audio from an mkv file and received the following message advising I post it here for review:

Traceback (most recent call last): 
File "model\extract.py", line 108, in selectFile 
File "model\extract.py", line 214, in __probe_file 
File "model\ffmpeg.py", line 341, in probe_file 
File "ffmpeg\_probe.py", line 20, in probe 
File "subprocess.py", line 800, in __init__ 
File "subprocess.py", line 1207, in _execute_child 
FileNotFoundError: [WinError 2] The system cannot find the file specified 

I'd be grateful for any help you can offer.

Thanks and regards
Rex

**Comment by olegkurchin** [comment]
What OS are you running? Try to specify where ffmpeg files are at your computer (go to Preferences > Binaries in BEQDesigner)

<img width="384" alt="Screenshot 2020-12-07 at 18 24 48" src="https://user-images.githubusercontent.com/5749140/101369670-a0094780-38b9-11eb-9a8a-c33e0f349a70.png">

If you don't have one, just download a package relevant to your OS from https://ffmpeg.org/download.html and specify the folder in BEQDesigner.

PS. Make sure your BEQDesigner version is 0.9.6-beta.5 or higher

**Comment by rexxyic4** [comment]
Thank you very much, this solved the issue.  I was running 0.95, so updated to 0.96 beta7 and then specified the ffmpeg folders as instructed.

**Comment by olegkurchin** [comment]
Good to hear. Enjoy - that's indeed very powerful app. 
Please mark the issue as solved
