### ISSUE TITLE
App crashes after "Extract" or "Remux" is complete (OSX)

### ISSUE THREAD

**Issue by olegkurchin** [3ll3d00d/beqdesigner#397]
Each time Extract or Remux procedure is complete for .avi file, app crashes. Though Extract or Remux completed successfully and all files are stored properly. v.0.9.7-beta v2. 
.mkv is OK

**Comment by 3ll3d00d** [comment]
Any logs available?

**Comment by olegkurchin** [comment]
Here're excerpts from crash window (actually two arise one after another)

[report_0.txt](https://github.com/3ll3d00d/beqdesigner/files/5719789/report_0.txt)
[report_1.txt](https://github.com/3ll3d00d/beqdesigner/files/5719790/report_1.txt)

**Comment by olegkurchin** [comment]
Not sure if such reports are helpful. Can do some specific loggin, just give me a hint. One thing I notice, is that it crashes with most .avi's, but not 100% of files

**Comment by 3ll3d00d** [comment]
hard to say what is going on there, it might be generating an error message from an unexpected place which then causes the UI to crash

if you run the ffmpeg command at the cli does it complete successfully?

**Comment by olegkurchin** [comment]
Found the reason for crash: non-english charset in .avi metadata. Once replaced with english (I use AVI MetaEdit) - works flawlessly.
