### ISSUE TITLE
Linked signals don't update when changing filters.

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#40]
Linked signals don't update automatically.  I added a bunch of signals with one main signal with all others linked.  If I update the filter and save, it doesn't reflect the changes on all signals until I go back into the Link dialog and hit save in there.

**Comment by 3ll3d00d** [comment]
I think this only happens in the following circumstances

- add signals
- last signal is selected in the table
- click link
- enslave the currently selected signal to some other signal

filter remains the filter for the previously selected signal instead of being the master signal
