### ISSUE TITLE
Direct import to minidsp

### ISSUE THREAD

**Issue by mrene** [3ll3d00d/beqdesigner#416]
I've been working on a utility for [controlling minidsp devices](https://github.com/mrene/minidsp-rs) that includes the ability to import PEQs in the current config. @bmiller mentionned it would be a great addition to this software on the minidsp forums. I'm opening this to get the discussion started.

Using direct commands has a few advantages over writing an xml config, notably you can choose to write the input PEQs directly without touching the rest of the configuration. Importing these is much quicker since you only have a few commands to issue instead of the entire config to load.

One way to integrate would be to ship the binary and give it a list of commands via a file (or stdin), each PEQ can be configured individually (I just added support for imporitng filters from REW's text format so you need to look at the `dev` branch for that feature).

There are cross builds for x86_64 debian/armv5hf (rpi0 compatible0) / osx x64 / windows x64 done at every release. Do you currently distribute binary artifacts for each platform? If yes it might be pretty simple to add something new.

**Comment by 3ll3d00d** [comment]
> Do you currently distribute binary artifacts for each platform? 

yes though x64 only atm (limited to OS provided by gh actions for builds so windows/macOS/ubuntu)

> One way to integrate would be to ship the binary and give it a list of commands via a file (or stdin), each PEQ can be configured individually

I had thought it would be nice to put a network interface on top of it, more work obviously but any plans to do that? I am under the impression that people using this app don't tend to connect the computer they use for beqd to the device itself (or would prefer to be remote from it) hence why I was thinking a remote api would be a good way to integrate. I could be wrong with this assumption though.

> I just added support for imporitng filters from REW's text format so you need to look at the dev branch for that feature

I'd be happy not to convert to another format, do you accept biquad coefficients directly? can I read current state as well? am I right in thinking that you overwrite the entire block of filters? i.e. if I supply 4 biquads when 10 are supported then the remaining 6 are cleared. There are certain merge modes which allow beq filters to be merged with existing config so to support this it would either need ability to specify slots to write into or be able to read what is there atm in order to ensure they remain in place.

**Comment by mrene** [comment]
> I had thought it would be nice to put a network interface on top of it, more work obviously but any plans to do that? I am under the impression that people using this app don't tend to connect the computer they use for beqd to the device itself (or would prefer to be remote from it) hence why I was thinking a remote api would be a good way to integrate. I could be wrong with this assumption though.

I was still debating whether to include an http/json api to make it easier for other apps to integrate. Right now `minidsp-rs` can expose the HID protocol over TCP, which is the same thing that their other product(WI-DG) does, which makes the app compatible with it (so you can use the official apps remotely as well). It doesn't hide away the complexities of their protocol though. At that point it's a matter of deciding whether users should install this separately or not, if most of your users have their devices hooked up to a board and are technically inclined enough to install this then it makes sense to expose things via http and publish instructions on how to configure it. It's not a crazy amount of work and I'd see myself using it over http as well.

> I'd be happy not to convert to another format, do you accept biquad coefficients directly? 

Oh that format is just the biquads coefficients in a text file.
```
biquad1,
b0=0.999194903557377,
b1=-1.9973354686174658,
b2=0.9981886333563846,
a1=1.9973354686174658,
a2=-0.9973835369137615,
```
You can always pass them directly too: `minidsp output 0 peq <index> set <b0> <b1> <b2> <a1> <a2>`

Or if you generate a command file (same format as the command line, without the repeated program name):
```
output 0 peq 0 set <b0> <b1> <b2> <a1> <a2>
output 0 peq 0 bypass off
output 0 peq 1 set <b0> <b1> <b2> <a1> <a2>
output 0 peq 1 bypass off
...
```
and then use `minidsp -f ./cmd-file`

> can I read current state as well?

The device's firmware doesn't allow state to be read back unfortunately. I do not keep state currently but it's something I'm considering in the future (so I could generate an up-to-date xml config for the occasional times where I want to use the plugin app). 

> am I right in thinking that you overwrite the entire block of filters? i.e. if I supply 4 biquads when 10 are supported then the remaining 6 are cleared. 

That is the behaviour if you use `peq all import ./filename.txt` but they are individually adressable so it's possible set them individually. `import` also un-bypasses the filter after setting it in case it was.

> There are certain merge modes which allow beq filters to be merged with existing config so to support this it would either need ability to specify slots to write into or be able to read what is there atm in order to ensure they remain in place.

Do users currently configure this inside beqdesigner? If we go the http route users could configure what filters are available for temporary use - or I could infer it from the fact that their coefficients aren't set.

**Comment by 3ll3d00d** [comment]
> Oh that format is just the biquads coefficients in a text file.

ah ok, is that the same format as used to create a custom biquad filter via the minidsp app? if so, I already create that via some other export format so can easily reuse that.

> Do users currently configure this inside beqdesigner? If we go the http route users could configure what filters are available for temporary use - or I could infer it from the fact that their coefficients aren't set.

yes, currently there is a dialog that lets them choose which type of minidsp device to use and which input or output channels to write to. I don't let them choose filter slots exactly just how many to allow me to write to and then I write from the bottom up. The use case here being integration with [MSO](https://www.andyc.diy-audio-engineering.org/mso/html/index.html) so someone can choose to have 4 shared filters in MSO leaving 6 input filters for BEQ to occupy (and hence potentially needing to use a few slots on the output channels as well as convention is that BEQ filters are designed to fit in the input channel so 10 biquads).

**Comment by mrene** [comment]
It's the same format as the minidsp app yes.

I just noticed a few xml configs for other minidsp products in your test fixutres, I'll start building device configs based on them to support other models.

Do you own any of their products? I'm looking for a way to tell them apart, like their respective usb product ids but that info isn't online.

**Comment by 3ll3d00d** [comment]
I don't even own a 2x4HD, it's just what most people use for this purpose. There are some people active on avsforum who do use the other products I have added support for (2x4, 4x10HD, 10x10HD, 88a) so posting on [that thread](https://www.avsforum.com/threads/bass-eq-for-filtered-movies.2995212/page-831#post-60405122) might elicit some data.

**Comment by 3ll3d00d** [comment]
published a build with support for this in https://github.com/3ll3d00d/beqdesigner/releases/tag/0.9.7-beta.12

**Comment by mrene** [comment]
That was quick :) 

I added support for reading cmds from stdin in the dev branch, so you'll be able to keep the subprocess open and write commands as you go `minidsp [optional transport options] -f -` and just write `output n peq m set .....\n` (until we have http)

**Comment by andyc56-mso** [comment]
I'm currently working on some mods to MSO that would help with BEQ as well.  The FlexASIO author requested Equalizer APO export, and this led me to a redesign of MSO's export capability to generalize it to multiple formats.  One mod is to lump in any shared filters into individual channels as you seem to be doing, freeing up the shared channel for BEQ (which I'm not familiar with).  Anyway, a 2x4 HD user would be able to have up to 10 individual biquads, plus as many as 8 shared biquads, and the overflow above 10, up to 8 extra, would be stuffed into the crossover biquads via a separate file for import. That will be in 1.0.47, but I am much lazier and slower than you guys.
