### ISSUE TITLE
Keyboard shortcut for Save Filter is the same as for Merge Signals. Mac build

### ISSUE THREAD

**Issue by CineManiac93** [3ll3d00d/beqdesigner#422]
Option+Command+S is the same for Save Filter as it is for Merge Signals

**Comment by 3ll3d00d** [comment]
I've changed merge to use ctrl+meta+s (which should mean cmd+ctrl+s on macos) so hopefully that fixes it, I don't have a mac to test this on though so let me know if this works as expected (qt docs are a bit vague on the subject)

**Comment by CineManiac93** [comment]
Looks good. Thank you, man.

Regards,

Tamim
