### ISSUE TITLE
I am unable to merge with my MiniDSP configuration .xml file a filter that I created in BEQ Designer.

### ISSUE THREAD

**Issue by DrewNeilson** [3ll3d00d/beqdesigner#435]
In the "user source directory" field that is inside of the "merge BEQ" function, I've entered a folder called "mine & others". In Windows Explorer, I've placed two folders inside of that folder: one called "mine", and one named after an AVSforum user whom posts images of filters in his thread but does not put the filters on GitHub. Since I have to manually enter the details for the filters that this user creates, I want to save those filters into their folder that I named after this user, and have _my_ filters be inside of the folder "mine". _My_ folder contains a folder called "Life Is Strange series", and that folder contains a folder called "Life Is Strange", which is a game that I've created an experimental filter for. Inside of _that_ folder I have saved the following:
an .xml file
a .beq file
a .filter file
a .signal file
I have been unable to use the merge function to create a .xml file that contains my experimental filter on the input side and my personal MiniDSP settings on the output side, even though the merge function works for filters that were created by other people and that are available on GitHub. I haven't tried recreating any of the filters posted by that other user and that I have to enter manually, so I don't know if BEQ Designer will merge those filters with my MiniDSP XML configuration file. Since it isn't doing that with my Life Is Strange filter, I doubt that it'd do it with any of the filters that this other user posted images and settings for.

**Comment by 3ll3d00d** [comment]
it's a bit hard to tell what you're doing, would help if you post a pic of the window and the folder structure. 

the "user source directory" feature simply works exactly as the public repos do, i.e. it searches under that path and attempts to take the filters from any xml file found & write them into an output file based on your base config. The structure inside that folder shouldn't matter and the presence of signal files or anything else should be completely irrelevant too. It just looks for files that end in .xml and treats them as a minidsp xml file that has some beq filters in it.
