### ISSUE TITLE
Name truncation on processing audio

### ISSUE THREAD

**Issue by Mobe1969** [3ll3d00d/beqdesigner#436]
This is a minor quibble but after processing over 3000 files I'd really appreciate it if it could retail wav and signal name.

Eg, just say when you process audio, the title is "intruder (2020) DTS-HD MA 5.1", when it finishes processing and had 

S the signal name, it is then "intruder (2020) DTS-HD MA 5", and over 3000 times I've had to correct it.

**Comment by 3ll3d00d** [comment]
try 0.10.2 when it is built
