### ISSUE TITLE
Trouble merging 10x10 or 4x10 configurations

### ISSUE THREAD

**Issue by luv2fly3** [3ll3d00d/beqdesigner#437]
I'm having trouble with using the 10x10 function, which I actually want to import to a 4x10 device. The filters appear to be applied to the output side on channels 1/2 and not on the input side.  I'm also seeing errors when saying "Yes" to the message which appears (image attached).  I'm attaching a copy of the error log, as well as a config file for the 10x10 and 4x10 so you can see both. Again, I'll probably use the 10x10 so that 6 filters can be applied vs the 5 of the 4x10.  

Thank you
[BEQ Errors.txt](https://github.com/3ll3d00d/beqdesigner/files/7698880/BEQ.Errors.txt)
![BEQ Merge Question](https://user-images.githubusercontent.com/96011067/145715942-9efb7253-6e34-4031-bf1c-b0861b71dd05.png)
[2x8 Config xml.txt](https://github.com/3ll3d00d/beqdesigner/files/7698895/2x8.Config.xml.txt)
[8x8 Config xml.txt](https://github.com/3ll3d00d/beqdesigner/files/7698896/8x8.Config.xml.txt)
!

**Comment by 3ll3d00d** [comment]
can you add 1 filter to each input and output channel pls, make each one different so it's easy to see which is which in the config

for example, use any Q and any frequency but match the gain to the channel

input 1, 20Hz +1dB 
input 2, 20Hz +2
input 3, 20Hz +3
input 4, 20Hz +4
output 1, 20Hz -1
output 2, 20Hz -2
output ....
output 10, 20Hz -10

**Comment by luv2fly3** [comment]
Hopefully this is what you need. I set eq 1 on each input to 10Hz with the gain level matching the input number. The outputs are set to 1000Hz also with the gain numbers corresponding to their channel numbers.  Again, this is for the 10x10 (8x8) which is probably what I'd use
[8x8 Test 2 xml.txt](https://github.com/3ll3d00d/beqdesigner/files/7699593/8x8.Test.2.xml.txt)
.

**Comment by 3ll3d00d** [comment]
thanks, it looks like the analogue inputs are in PEQ_11 to PEQ_18 and the analogue outputs are in PEQ_1 to PEQ_8

**Comment by 3ll3d00d** [comment]
the current 10x10 function already writes filters to those channels (PEQ_11 to PEQ_20) so this should already be working as designed

one missing feature is to avoid that optimise step and allow it to write filters across inputs and outputs

the 4x10 device isn't supported at all right now, the file attached to the original post as PEQ_1 to PEQ_14 so I'd guess the analogue inputs are PEQ_11 and PEQ_12 but that's just a guess

I'm confused as to what you're trying to achieve now though as the 10x10 is already supported and should work (subject to the existing 6 filter limitation which you either ignore and accept some filters can't be used or attempt to workaround automatically)

**Comment by 3ll3d00d** [comment]
no response so closing
