### ISSUE TITLE
Move side panel in reference window so the chart is always the same size

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#440]
>  Is there any reason the side panel isn't fixed width?

because I'd never noticed it before you just mentioned it :) (and also because doing any gui layout work is a fiddly PITA)

practically speaking fixing the size would mean moving the dropdowns out of that dialog so the chart is always the same size for a given dialog window size

i don't think there is any other reason why the dimensions of the chart itself should vary, the contents might vary depending on how big the axis labels are though

_Originally posted by @3ll3d00d in https://github.com/3ll3d00d/beqdesigner/issues/438#issuecomment-999869603_

**Comment by Mobe1969** [comment]
Cheers!

**Comment by 3ll3d00d** [comment]
@Mobe1969 0.10.6 (should be up shortly) contains a "hide sidebar" toggle on that screen which should mean the chart will be same size every time (assuming the dialog itself is left at same size). Let me know if that does the job.

**Comment by Mobe1969** [comment]
Thanks Matt!

**Comment by Mobe1969** [comment]
One issue with this, once you hide the sidebar you can't hit the compare button, and no shortb0cut forcthem button. So can't hide until a compare done, then it redraws again, then you save

**Comment by 3ll3d00d** [comment]
quick workaround for this is autohiding that part of the dialog when you click compare
