### ISSUE TITLE
Hide Sidebar issue

### ISSUE THREAD

**Issue by Mobe1969** [3ll3d00d/beqdesigner#441]
Once you hide the sidebar you can't hit the compare button, and no shortb0cut for the button. So can't hide until a compare done, then it redraws again, then you save. So not saving any time.

If there was another compare over the right it'd fix this.

**Comment by 3ll3d00d** [comment]
I don't follow, why would you need to press compare again? because you've changed what you're comparing?

**Comment by 3ll3d00d** [comment]
no response so closing
