### ISSUE TITLE
Defaults Continued

### ISSUE THREAD

**Issue by Mobe1969** [3ll3d00d/beqdesigner#458]
When you save the report (File -> Save Report), if the report name could default

![Report Name](https://github.com/3ll3d00d/beqdesigner/assets/46695255/a3a1afcd-97ec-4e8d-8b09-92a2863c2562)

When you save the report, if you could make the file name the signal name:

![Report File](https://github.com/3ll3d00d/beqdesigner/assets/46695255/4b605776-079f-4e0d-960f-679327d97dd3)

When you save the heat map, it is trimminf the trailing ".1" for example on "Chickenhare and the Hamster of Darkness (2022) DTS-HD MA 5.1"
![Peak Spectrum Name](https://github.com/3ll3d00d/beqdesigner/assets/46695255/94748f15-6041-410e-94b2-4a65a578373f)

It might depend on the length of the file name as it doesn't always seem to do this - but this one is repeatable.

**Comment by 3ll3d00d** [comment]
> When you save the report, if you could make the file name the signal name:

this one is already in the latest release, it works for me as far as I can see.

**Comment by 3ll3d00d** [comment]
fixed the replaced file suffix + added report name + export beq

**Comment by Mobe1969** [comment]
> this one is already in the latest release, it works for me as far as I can see.
I just tried, latest beta, and it is blank. This is the standard File + Save Report, select image, then click save:
![image](https://github.com/3ll3d00d/beqdesigner/assets/46695255/ed553557-a521-4e45-915d-fa375168f94b)

**Comment by 3ll3d00d** [comment]
the pic gave me a clue

apparently you're in "pixel perfect" mode whereas I'm not

I had forgotten that existed :) will fix in next release

**Comment by 3ll3d00d** [comment]
in 1.0.0-beta.4

**Comment by Mobe1969** [comment]
> the pic gave me a clue
> 
> apparently you're in "pixel perfect" mode whereas I'm not
> 
> I had forgotten that existed :) will fix in next release

Thanks. I think it is perfect now! Thanks so much! Will save me a lot of copy and pasting.

**Comment by Mobe1969** [comment]
Ah, sorry about this, but an introduced bug / change with this last one - the report is now saving as a PNG rather than a jpg. Previously it was jpg. So every other file I have done in the repo is jpg. So for consistency I have to change it manually somehow

**Comment by 3ll3d00d** [comment]
I assumed pixel perfect meant top quality too :)

Will add an option somewhere in next build

**Comment by Mobe1969** [comment]
I try to keep image files as small as possible! I actually compress / level using xnview after. I only have so much space in the repo. I keep wondering when I'll need to buy space or find some other automatable solution.

**Comment by Mobe1969** [comment]
BTW, if you have that new JPG default option apply to the Peak Spectrum file too, that'd be great.

**Comment by 3ll3d00d** [comment]
I think 1.0.0-beta.5 covers all of those but lmk if I missed any
