### ISSUE TITLE
Preservation of BEQ Metadata if existing metadata in XML Filter when saving

### ISSUE THREAD

**Issue by Mobe1969** [3ll3d00d/beqdesigner#459]
If possible can we have the File -> Save XML Report preserve the BEQ Metadata section on save, if the XML file already exists?

Eg, if file exists, read it, add the metadata to the xml document, and then save.

Thanks

**Comment by 3ll3d00d** [comment]
assume you mean File > Export BEQ Filter?

if so, try 1.0.0-beta.7

**Comment by Mobe1969** [comment]
> assume you mean File > Export BEQ Filter?
> 
> if so, try 1.0.0-beta.7

Thanks!!!!! I'll try it out when my internet is back up at home...

**Comment by Mobe1969** [comment]
Just a note on this - I think there is an issue with the encoding when it saves it. Eg I just updated wheel of time and it preserved the metadata, but the encoding was wrong on the save so it broke the catalog build.

I just regenerated the metadata clean, and as you can see in the image, one is the before (the preserved broken one) and the after is the clean regenerated version.

![image](https://github.com/3ll3d00d/beqdesigner/assets/46695255/7dc28ba3-7cb6-4c4e-93ad-38d6c8965166)

**Comment by 3ll3d00d** [comment]
seems a windows specific problem, I don't see the same behaviour on linux

**Comment by 3ll3d00d** [comment]
just to check, you're saying it resulted in this change

https://github.com/Mobe1969/miniDSPBEQ/commit/fc80048f4dbaedabe5f33f5d00da64965722061f

**Comment by 3ll3d00d** [comment]
should be fixed in beta11

**Comment by Mobe1969** [comment]
Thanks.

Yes I've tried saving that filter a few times, and I'm not seeing it now! Thanks.
