### ISSUE TITLE
AttributeError: module 'warnings' has no attribute 'warning' [11912] Failed to execute script 'app' due to unhandled exception!

### ISSUE THREAD

**Issue by Philotto** [3ll3d00d/beqdesigner#462]
Hi, when i have download the latest version for windows, when i try to open the .exe, then appear those message and close the application instantly

Traceback (most recent call last):
  File "app.py", line 1383, in <module>
  File "app.py", line 1377, in make_app
  File "qdarkstyle\__init__.py", line 437, in load_stylesheet_from_environment
AttributeError: module 'warnings' has no attribute 'warning'
[11912] Failed to execute script 'app' due to unhandled exception!

**Comment by 3ll3d00d** [comment]
Latest prerelease?

**Comment by Philotto** [comment]
The 1.0.0


Filippo Sanchez

Il mer 18 ott 2023, 08:26 Matt Khan ***@***.***> ha scritto:

**Comment by Philotto** [comment]
The 1.0.0
I have deleted the old version (a release like from 2 years ago) and
downloaded the latest 1.0.0 , but when try to run it then appear this
message and instantly close

Filippo Sanchez

Il mer 18 ott 2023, 08:26 Matt Khan ***@***.***> ha scritto:

**Comment by 3ll3d00d** [comment]
it's related to a value in this registry key 

`HKEY_CURRENT_USER\SOFTWARE\3ll3d00d\beqdesigner\style\matplotlib_theme` 

it will be set to `beq_dark_extra`

change it to `beq_dark` and restart

**Comment by Philotto** [comment]
super ! resolved !
