### ISSUE TITLE
Problem using image from URL in report

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#464]
> Hi, when i try to upload an Image from URL i get this error:
> 
> ```
> Traceback (most recent call last): 
> File "model\report.py", line 787, in load_image_from_url 
> File "model\report.py", line 712, in apply_image 
> File "matplotlib\image.py", line 1563, in imread 
> File "PIL\Image.py", line 3280, in open 
> PIL.UnidentifiedImageError: cannot identify image file 'D:\\TEMP\\tmpccvwki15.jpg' 
> ```

_Originally posted by @Philotto in https://github.com/3ll3d00d/beqdesigner/issues/463

**Comment by 3ll3d00d** [comment]
@Philotto what's the URL of the image? or does it happen for every URL you try?

**Comment by Philotto** [comment]
I have tried 2 url but does it happen the same, example this:
https://images.fanart.tv/fanart/barbie-64f783a353aa1.jpg

Or this:
https://images.fanart.tv/fanart/atomic-blonde-59aea3c3be015.jpg

**Comment by 3ll3d00d** [comment]
the problem is that that site is blocking a direct download, if I hit it in a browser then I get some captcha first and from cli it hits some html page

**Comment by 3ll3d00d** [comment]
I can make it provide a better error but that's about it

![image](https://github.com/3ll3d00d/beqdesigner/assets/2487509/0420a62e-9b69-4106-9505-ad0cc9511254)
