### ISSUE TITLE
Unexpected Error detected saving report

### ISSUE THREAD

**Issue by kaelaria** [3ll3d00d/beqdesigner#465]
I opened a saved project, created the report, clicked save:

Unexpected Error detected, go to https://github.com/3ll3d00d/beqdesigner/issues/new to log the issue
Traceback (most recent call last): 
File "model\report.py", line 508, in accept 
File "model\report.py", line 512, in __save_report 
File "model\report.py", line 537, in __get_report_file_name 
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by kaelaria** [comment]
It shows no signal other than the chart

![66](https://github.com/3ll3d00d/beqdesigner/assets/44355495/2bc9224a-7caa-401d-8f04-2b6c6096fda3)

**Comment by 3ll3d00d** [comment]
both issues appear to be symptoms of the underlying signal file no longer existing in the location the project thinks it is, not sure how exactly you arrive in that situation but you can attach the beq file to this issue to look into it.

**Comment by 3ll3d00d** [comment]
[1.0.2](https://github.com/3ll3d00d/beqdesigner/releases/tag/1.0.2) has a small tweak that should stop it producing an error in this situation

**Comment by kaelaria** [comment]
Nothing changed with the material, everything is in it's own directory.  I just started a new project, loaded in the signal and saved filter, it worked fine.  It was just something wonky with that saved project file.

**Comment by 3ll3d00d** [comment]
If you share the file, it may be possible to work out what the issue was

**Comment by kaelaria** [comment]
I already overwrote it when I fixed it
