### ISSUE TITLE
exe not opening 

### ISSUE THREAD

**Issue by jt23738** [3ll3d00d/beqdesigner#469]
beqdesigner_2022Server.exe

every version with that filename does not open. versions with the beqdesigner_10.exe name open fine. 

![Recording 2024-04-13 224247 - frame at 0m12s](https://github.com/3ll3d00d/beqdesigner/assets/77703254/b03e518f-599a-4302-8d93-0bbb1f0dd005)

**Comment by 3ll3d00d** [comment]
I cannot reproduce on any windows machine I have including a fresh win10 VM so this looks like a local issue to me

**Comment by 3ll3d00d** [comment]
appears to be the same issue as https://github.com/spyder-ide/qtawesome/issues/236 so perhaps that thread gives you some ideas on how to workaround it

**Comment by LukeNuk3m** [comment]
i had the same issue today and rebooting the PC seems to have fixed it
