### ISSUE TITLE
Support for minidsp Flex HTx

### ISSUE THREAD

**Issue by conrad-nash** [3ll3d00d/beqdesigner#470]
Currently the Flex HTx doesn't work with minidsp-rs. I would like to be able to run the merge process within BEQ designer and have it output HTx compatible files.

I've attached an empty xml from the device console connected to my HTx, as well as an XML file that has a variety of filters and settings applied. A screenshot of the main screen is also provided so that you can see where the filters and settings are applied.

![image](https://github.com/3ll3d00d/beqdesigner/assets/42913019/f738391b-183c-4b72-bc55-2d32757640c4)
[Flex HTx.zip](https://github.com/3ll3d00d/beqdesigner/files/15418562/Flex.HTx.zip)

**Comment by 3ll3d00d** [comment]
if you diff those two files, there are a lot of differences that don't appear to be from a BEQ (e.g. polarity inversion,  some gain change, changes to what minidsp refers to as a bandpass filter which I guess means the xo slots)

the BEQ stuff seems standard so will deal with that but will ignore the other stuff

**Comment by 3ll3d00d** [comment]
initial impl in https://github.com/3ll3d00d/beqdesigner/releases/tag/1.1.3

**Comment by 3ll3d00d** [comment]
give it a try and see if it works (obviously measure to verify rather than just using it)

**Comment by conrad-nash** [comment]
Just tested.
It's maintaining the previous existing config, but it's only loading the filters to the first two output channels, not all eight.

Let me know if you want a file with specific filters on each output channel so that you can see where they live in the config file.

I've attached the source (my personal eq across eight channels, all crossover based) and the merged output of BEQd.

[Merged output of BEQd.zip](https://github.com/3ll3d00d/beqdesigner/files/15443800/Merged.output.of.BEQd.zip)

**Comment by 3ll3d00d** [comment]
Thanks, do you need to be able to choose which channels to apply the filters to?

**Comment by conrad-nash** [comment]
I don’t but I’m using all 8 outputs. Someone that was using fewer might want that control. Although if they’re not using the outputs it wouldn’t matter? Maybe if they’re using an output for a TR device you might not want the BEQ applied?

But for me, no.

**Comment by 3ll3d00d** [comment]
should be fixed in 1.1.4

**Comment by 3ll3d00d** [comment]
seems there's some logic that assumes 1 & 2 are input channels, tricky business working with code untouched for years!

**Comment by 3ll3d00d** [comment]
should be fixed in https://github.com/3ll3d00d/beqdesigner/releases/tag/1.1.5
