### ISSUE TITLE
Error when saving merged spectrum

### ISSUE THREAD

**Issue by TythorZeth** [3ll3d00d/beqdesigner#473]
Hey, I get an error when I want to 'Save Chart' (spectrum) of the merged episodes of S03 Mayor of Kingstown. It asks for the size in pixels, and when clicking 'Ok' this error emerges, without making an image:

Traceback (most recent call last): 
File "app.py", line 1181, in accept 
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by 3ll3d00d** [comment]
pls give exact steps to reproduce as there are multiple ways to end up at that point in the code so I need to know how to get to the above situation

I mean from opening the app like, my guess is you do something like

add multiple tracks as signals
merge them
save chart via one of the available options

but there's lots of ways to get here so I can't fix reliably without knowing that

**Comment by 3ll3d00d** [comment]
small change in next build should stop it blowing up though good to know why it happens so I can possibly fix the root cause
