### ISSUE TITLE
Unable to load part of a wav

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#51]
app allows you to specify start/end times but it seems to load the whole thing anyway

**Comment by aron7awol** [comment]
This now works properly in the preview but when I add the signal it still uses the entire file

**Comment by aron7awol** [comment]
This still doesn't seem to be working for me.  I can specify a time range and hit Preview and the preview looks correct, but when I add the signal it adds the entire signal, ignoring my time range.

**Comment by 3ll3d00d** [comment]
it works fine for me, can you give step by step instructions on exactly what you are doing?
