### ISSUE TITLE
Specify image in report generator by web address?

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#62]
Is this a simple enhancement?

Since the artwork always comes from the web, when I currently post a BEQ, I copy and paste the web address for the image into the post.  It would be really nice to be able to do the same in BEQ Designer.

**Comment by 3ll3d00d** [comment]
it depends where the image comes from & whether any authentication or api key is required

is there a particular site or were you just thinking of pasting in an arbitrary url?

**Comment by aron7awol** [comment]
I was thinking of just pasting in a plain URL.  

Being able to search fanart sites from within the app would be a fantastic addition if that's something you're open to in the future.  I've been using Movie Thumbs from fanart.tv

**Comment by 3ll3d00d** [comment]
fanart api search -> https://fanarttv.docs.apiary.io/#reference/movies/get-movies/get-images-for-movie

**Comment by 3ll3d00d** [comment]
I think putting the search in the app will be a fair bit of effort and basically does no more than what your browser already does 

downloading an image via a URL is easier though

**Comment by aron7awol** [comment]
I agree, specifying an image via URL is good enough
