### ISSUE TITLE
Upload Chart/Report to imgur

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#64]
This would be another great addition.  If user can provide API key for imgur, and the app can upload the Chart/Report directly to imgur, and ideally, copy the link to the image to the clipboard.

**Comment by 3ll3d00d** [comment]
imgur api details -> https://apidocs.imgur.com/

**Comment by 3ll3d00d** [comment]
qt clipboard -> http://doc.qt.io/qt-5/qclipboard.html#details

**Comment by 3ll3d00d** [comment]
no plans to implement this so closing
