### ISSUE TITLE
Report filter block - Change font size, make background opaque

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#65]
I want to move to using the report for my BEQs but I think these couple of minor changes are necessary first:

1. Be able to change the font size in the filter block
2. Be able to make the filter block have an opaque background

**Comment by 3ll3d00d** [comment]
font size in the table is surprisingly hard to get to behave reliably when it is user controlled, can give it another go but not sure that will work well. Do you just want it to be bigger or does it need to vary in some way?

I don't understand point 2, what is behind the table that you want to be able to see?

**Comment by aron7awol** [comment]
Font size just seemed too small to read.  This might have something to do with the fact I am on a 4K screen, as I've noticed others' graphs look different from mine.  Bigger but not user-adjustable would be perfectly sufficient.

I want the background of the filter block to be fully opaque, not able to be seen through at all.  The issue was that the gridlines were appearing behind the filter block and making the already difficult to read text ever harder to read.

**Comment by 3ll3d00d** [comment]
Can you add a pic of how it looks on your screen pls.
