### ISSUE TITLE
Add filter block to chart

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#66]
I've been using the report, and it's working pretty well, but the report image is ending up very large.  A big reason for this is that JPEG is a logical format for the image, but PNG is a logical format for the chart.

If you add the filter block to the chart exactly as you have it in the report, I can save the chart and filters as PNG and leave the image as JPEG.

**Comment by 3ll3d00d** [comment]
not sure I follow

why does it matter if the image is big?

**Comment by aron7awol** [comment]
I am just concerned that they are ending up between 1.25-2.5MB each.

The image is only ~300KB
The chart is only ~125KB
