### ISSUE TITLE
When using filter x3, it shows as X.99999999 and overflows

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#75]
![image](https://user-images.githubusercontent.com/42757020/46263955-76d41c00-c4e4-11e8-87c8-8b1f1dc6cb6b.png)

x2, x4, x5 work fine.  It looks like multiples of 3 have the same issue as x6 did the same.

**Comment by 3ll3d00d** [comment]
fwiw it is the total that is not rounded on formatting rather than than the multiplier

**Comment by 3ll3d00d** [comment]
released in https://github.com/3ll3d00d/beqdesigner/releases/tag/0.3.1
