### ISSUE TITLE
Support rescaling an image to match the chart size

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#76]
I do agree that rescaling the image (high quality rescale ideally) to the chart size and then combining the two into a single image is a great approach.  That's the ideal approach in my mind.

_Originally posted by @aron7awol in https://github.com/3ll3d00d/beqdesigner/issues/69#issuecomment-425909679_

**Comment by 3ll3d00d** [comment]
https://pillow.readthedocs.io/en/5.3.x/reference/Image.html#PIL.Image.Image.resize can be used with a lanczos filter which should yield a high quality result with very little coding effort

**Comment by 3ll3d00d** [comment]
@aron7awol added in https://github.com/3ll3d00d/beqdesigner/releases/tag/0.3.2

**Comment by aron7awol** [comment]
Thanks!  I'll try this one now!

**Comment by 3ll3d00d** [comment]
Use the same pixel perfect mode (should probably rename that), it will rescale the image to match the chart size. The button next to the size will snap the chart to the aspect ratio of the picture btw

**Comment by aron7awol** [comment]
When using pixel-perfect mode, the image is supposed to disappear, right?

In any case, it works awesome!  Thanks!

**Comment by aron7awol** [comment]
Did you also increase JPEG quality in this change?  I'm just curious because I think I'm seeing a doubling in resulting filesize compared to the previous release for an image of similar size.

**Comment by 3ll3d00d** [comment]
yes the image is supposed to disappear as it is combined with the visible chart when you save it

I didn't change jpeg quality in this release, it has been set to quality=95 throughout. However the image rescaling does save with chroma subsampling turned off so my guess is that accounts for the change.

**Comment by 3ll3d00d** [comment]
if the file size is an issue then I could add a control for setting the quality level

**Comment by aron7awol** [comment]
It doesn't really affect me as I have a fast connection, I was just trying to be sensitive to people on slower connections.

They had been coming in typically around 750KB on the previous release and they are now about 1.5MB.  If you think that's acceptable for the average user then I'm good with it.
