### ISSUE TITLE
Report does not allow user to set graph limits

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#78]
On the normal graph, the app auto-selects the y-scale limits, but it can be overridden by the user with the Graph Limits dialog.  However, in the report generator, it reverts back to the auto-selected scale and I don't see a way to override it.

This isn't a major issue, just a consistency thing as I try to release every graph with -10 to -70 on the y scale.

**Comment by 3ll3d00d** [comment]
the limits button is there and seems to work

![image](https://user-images.githubusercontent.com/2487509/46375446-5abeaf00-c68b-11e8-96a4-7c6b2f50ffe8.png)

**Comment by aron7awol** [comment]
Hmm, I must have just missed that button when I was looking for a way to adjust the limits.  Thanks!
