### ISSUE TITLE
Extract audio does not work with DDP5.1 audio

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#8]
![image](https://user-images.githubusercontent.com/42757020/44694509-d483cd00-aa3b-11e8-9a82-c43eedaa6082.png)

**Comment by aron7awol** [comment]
I am including a DDP5.1 and a stereo EAC3.  Both fail with the same error.

[json.zip](https://github.com/3ll3d00d/beqdesigner/files/2328276/json.zip)

**Comment by 3ll3d00d** [comment]
I don't think this is an each issue as such, seems more likely to be a function of the way the file was ripped.

I think the sensible thing to do here is allow the user to specify the channel layout, I could probably guess and provide a default though.

**Comment by aron7awol** [comment]
Agreed, I think that would be a great solution.  I'll keep trying other files to see if I can find others that fail.

**Comment by aron7awol** [comment]
FYI, so far, every EAC3 file I've encountered so far is missing channel_layout.  I did some research and this has caused a bug on multiple other projects.  In those cases, they guessed based on channels, as you are planning.

**Comment by 3ll3d00d** [comment]
https://github.com/3ll3d00d/beqdesigner/releases/tag/0.0.1 should fix this, let me know if still having issues though
