### ISSUE TITLE
Allow user to select a time range when extracting/remuxing audio

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#89]
_Originally posted by @aron7awol in https://github.com/3ll3d00d/beqdesigner/issues/38#issuecomment-428397318_

**Comment by aron7awol** [comment]
Wow, you did this faster than I expected!  Can I ask how it works?  Specifically, does it have to re-encode the video at all or does it cut at keyframes or does it only re-encode what you cut before and after a keyframe?  I'm guessing you're using however ffmpeg does it so I'll do research on it in the meantime.  Thanks!

**Comment by 3ll3d00d** [comment]
See input seeking in https://trac.ffmpeg.org/wiki/Seeking

**Comment by 3ll3d00d** [comment]
Note that atm I only ever copy video, no transcode at all
