### ISSUE TITLE
Error when trying to map signals in remux dialog

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#94]
Double-clicked on a channel to map signal and received this error

![image](https://user-images.githubusercontent.com/42757020/46842654-be885c80-cd9c-11e8-9682-f0934b981457.png)

**Comment by 3ll3d00d** [comment]
I will need specific steps to reproduce this in order to investigate

**Comment by 3ll3d00d** [comment]
actually no need, this one is simple to fix
