### ISSUE TITLE
Apply filters to peak spectrum chart

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#98]
I just posted a peak spectrum chart in the BEQ thread and had an idea.  I think it would be awesome if there was an option to apply the filters to the peak spectrum chart.

**Comment by 3ll3d00d** [comment]
it's not possible to do this without applying filters to the source audio track so this is already covered by the "remux audio" dialog so you just have to go through that screen instead.

**Comment by aron7awol** [comment]
I totally understand if it's something that you don't want to spend time on, but I'm trying to understand why it's not possible.  I thought the data behind the chart would need to be transformed just as the data behind the PvA chart is.

I realize the implementation is complicated by the fact that the PvA chart supports multiple signals and filters for each signal, which is not something you'd want to duplicate for this purpose.  I was imagining a simpler implementation that supports a single signal, and I thought rather than have to duplicate the filter creation functionality at all, maybe it could be something that the user launches right from the main screen by selecting a signal and clicking a "peak spectrum" button and it displays a peak spectrum chart for the selected signal with its filters applied to the data.  This chart is essentially read-only other than changing the view parameters that already exist, and if they want to change the filters they can exit the peak spectrum screen and go change whatever they want to change on the main PvA screen.  Does that seem reasonable or is there a key piece to the implementation that I'm not thinking of?

**Comment by 3ll3d00d** [comment]
actually I think I was thinking of something else, you're referring to https://www.avsforum.com/forum/113-subwoofers-bass-transducers/2995212-bass-eq-filtered-movies.html#post56946934 right and you want to see that view for the current signal with the current filters applied?

**Comment by aron7awol** [comment]
Yes, exactly!

**Comment by 3ll3d00d** [comment]
ok that is feasible

**Comment by 3ll3d00d** [comment]
@aron7awol just to be clear, in this case feasible doesn't mean "small amount of work" unfortunately. I don't actually keep the content required to create this view in memory atm and hence it isn't saved to disk either in the signal or project formats. This means I would need to keep that data in memory & either make those file sizes much bigger or only make this option available if the data is available.

Nothing difficult in here but it's a relatively invasive, and hence time consuming, change

**Comment by aron7awol** [comment]
Gotcha.  What if, instead, you simply added the ability to apply a signal's filters when generating a peak spectrum?

If I understand how the app works, the issue in going from a current signal with filters to a peak spectrum with filters, is that only the data for the PvA chart is in memory.  In order to create a peak spectrum graph, the necessary data would have to be loaded from the original wav file, which in the case of loading a saved signal, does not necessarily exist.  A solution that would work in some cases would be to save the path to the wav file (and the timestamps of the snip taken if applicable) along with the signal data, but we are now presuming the file still exists at that path.

Rather than having that possibility of the saved path becoming invalid, perhaps a more elegant solution would be to add the ability to apply a current signal's filters when generating a peak spectrum graph.  Since generating a peak spectrum graph already requires the original wave, all of the data required is already being loaded from the file, then the additional step is to apply the filters to that data before displaying it.  I am envisioning a single drop-down box that the user can choose a current signal whose filters will be applied to the peak spectrum data, or they can choose nothing and it will generate it without filters as normal.

I realize I don't fully understand how everything works and I'm guessing at a lot of it, but does what I'm thinking make sense?

**Comment by aron7awol** [comment]
That's great!

I think the post-BEQ peak spectrum is something I should publish along with the PvA graph.  In some ways, it will be even more illustrative of the impact of a given BEQ than the PvA graph.

**Comment by 3ll3d00d** [comment]
interestingly it only takes about 1s on my laptop to apply a whole bunch of biquads to a 48kHz signal that is ~1.45hrs long (aka typical film length), rather longer to load the track into memory but the filtering itself is quick enough to not have to think about it

**Comment by aron7awol** [comment]
Wow, that is shockingly fast!

**Comment by 3ll3d00d** [comment]
implemented in https://github.com/3ll3d00d/beqdesigner/releases/0.4.3
